### ISSUE TITLE
[QA] Incomplete instructions how to install linux package

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10585]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

`sudo apt install apt-transport-https` missing in instructions how to install linux package

### Steps to reproduce the issue

Run commands in https://download.owncloud.com/desktop/ownCloud/testing/3.2.1.10355/linux/download/ for Ubuntu 22.04

### Screenshots

No screenshots

### Expected behavior

3.2.1.10355 client installed

### Actual behavior

2.6. client installed

**Comment by fmoc** [comment]
The main issue is the lack of an instruction to install `apt-transport-https` on Debian-based systems (to make sure it is installed). Once installed, the repository can be used as expected.

**Comment by fmoc** [comment]
Fixed, see https://download.owncloud.com/desktop/ownCloud/daily/3.2/linux/download/.

**Comment by HanaGemela** [comment]
Still missing in https://download.owncloud.com/desktop/ownCloud/daily/4.0/linux/download/

**Comment by HanaGemela** [comment]
Still no Debian builds but passed for Ubuntu 4.0 builds

**Comment by fmoc** [comment]
You must be working with some outdated cache or something. It's set up for *both* Debian and Ubuntu.

![screenshot_2023-03-20_10-00-23](https://user-images.githubusercontent.com/80399010/226292691-1eda7848-4121-4b86-974e-f41d30a3aace.png)
