### ISSUE TITLE
ownCloud desktop client asks for password with every boot and logins even if you cancel the password prompt.

### ISSUE THREAD

**Issue by sudhirkhanger** [owncloud/client#1902]
There are two issues with ownCloud desktop client.

1. It asks for password with each system login.
2. It can login if you click cancel.

I am running ownCloud desktop client v1.6 from OBS on Fedora 20 KDE. ownCloud desktop client password is saved and always allowed in KWallet.

**Comment by tiktaktok** [comment]
I combined previous answers into a script and now it works. 

Complete solution described here:
http://the-technoholik.blogspot.ch/2015/01/owncloud-client-asking-for-password.html

**Comment by daeavelwyn** [comment]
Hi tiktaktok,

Sorry, but your script doesn't solve the problem for me :-/

**Comment by tiktaktok** [comment]
You have to know that it's more of a workaround than a solution. In my case I could reproduce the bug by starting and killing kwalletd.  kwalletd not being started was clearly causing the ownCloud client to prompt for password.

Also my wallet is not protected by a password, so I suppose it's "unlocked" as soon as KWalletd is started. If yours is still locked and the timeout expires, the ownCloud client will ask for the password.

**Comment by tiktaktok** [comment]
The fix happens to work on Kubuntu 14.04.1 which runs KDE 4. On my Arch Linux machine running KDE 5, the fix doesn't work, but I've noticed that kwalletd crashes at launch, so there is no way ownCloud can get its password. Do you also have this problem?

**Comment by danimo** [comment]
Implementing https://github.com/frankosterfeld/qtkeychain/issues/25 would fix this. I'll try to tackle it for 1.8.1.

**Comment by dcrobertson01** [comment]
Hi - possibly  not related to the bugs above, but for the benefit of anyone else having a login problem with KDE Wallet and the owncloud client, here is another possible solution.

In my KDE Wallet, I had two password entries for Owncloud - both for the same server, but one for https:// and the other for http://

Deleting one of the passwords seems to have fixed the problem.

**Comment by danimo** [comment]
This should be fixed in 1.8.4, because we're shipping with a KDE Plasma 5-ready kwallet now.

**Comment by yan-** [comment]
Unfortunately I am having the same problem with version 1.8.4-1 on Kubuntu LTS. So it looks like it wasn't fixed in 1.8.4.

**Comment by daeavelwyn** [comment]
As Yan- mentioned, I also still encounter this issue. But it seems kubuntu 14.04 use mainly qt4, so perhaps using kde5 is the only solution to solve this issue :-/

**Comment by aHcVolle** [comment]
I've still got this problem on my arch machine using plasma ....
But its working fine on my arch notebook using plasma ... I couldn't track the differences yet

**Comment by ogoffart** [comment]
Do you use the packages provided by owncloud, the distribution packages, or something you compiled yourself?

**Comment by aHcVolle** [comment]
i'm using the package provided by archlinux (https://www.archlinux.org/packages/community/i686/owncloud-client/)

**Comment by ogoffart** [comment]
@aHcVolle do they have the same version of qtkeychain?

**Comment by aHcVolle** [comment]
i'll have to look when i'm back at home but i'd guess yes since both machines should be up2date.

**Comment by aHcVolle** [comment]
both have qt-keychain-qt4 & qt-keychain-qt5 with version 0.5-1
what i don't get is:
when i open kwalletmanager i have 1 wallet called "kdewallet" (which i also get a popup for after my pc is booting)
i just deleted it and created a new wallet called "kdewallet" with no password.
when i reboot owncloud-client is still asking for a password to open the wallet "kdewallet". Only if i enter my users' pw it will open (not when i leave the pw prompt empty). When i start chrome its using the just created "kdewallet" (with no pw). Even if i set a password for "kdewallet" owncloud will ask for a mysterious wallet called "kdewallet" protected with my users pw.
So i guess owncloud is using a different wallet that i have no idea how i can get access (and maybe change the pw).
reminder: its working as expected on my notebook
would a owncloud log help to debug this?

**Comment by dragotin** [comment]
Thanks for clearification.

**Comment by yan-** [comment]
I don't think that this bug exists due to a "lack of linux skills". When I install a new program, I expect it to work without me having to investigate and change general KDE settings. And actually even with aHcVolle's description I can't manage to 'solve' the problem.

Since a couple a weeks the message I get has changed to "Reading from keychain failed with error: 'No keychain service available'"

**Comment by dragotin** [comment]
@yan- but that sounds as if your kwallet is not started. Try to start the wallet system and have it started automatically on desktop startup. The thing is that this all depends heavily on the local settings of your system.

**Comment by daeavelwyn** [comment]
Ok, here are the steps I use to solve this issue.
First of all, you have to be sure you use the right libqtchain version (0.5), this lib is installed automatically with owncloud on my ubuntu 14.04 with open suse official repository.

Then you have to create set some stuff in kwallet. Go to settings > Account details > KDE wallet.
Check "activate kde wallet sub-system"  (or something like that, my system is in french so i'm not sure about translation, but I join screenshot). 
![owncloud-kwallet1](https://cloud.githubusercontent.com/assets/4292225/10815603/732ac500-7e2d-11e5-92e7-989e26c0b5fe.png)

Now create (if not exists) a defaut wallet called kdewallet and enter NO PASSWORD !
![owncloud-kwallet2](https://cloud.githubusercontent.com/assets/4292225/10815609/7c19771a-7e2d-11e5-85d8-57a17be52b0b.png)

now, go to settings > startup and shutdown and add kwalletd (see screenshot)
![owncloud-kwallet](https://cloud.githubusercontent.com/assets/4292225/10815587/5f415982-7e2d-11e5-9380-ed6c0a0867ad.png)

Restart your computer and it should work (at least I hope :-/ )

**Comment by yan-** [comment]
That seems to be a valid workaround. Thanks dragotin and daeavelwyn.

**Comment by yan-** [comment]
I have to retract from what I said before, it's not really working. Kwallet starts but it doesn't open the wallet and Owncloud Client asks me for the password. At the same time, Kwallet doesn't stay in the background, so I have to minimize it manually. Annoying. I wish Owncloud Client just saved the password internally...

**Comment by aHcVolle** [comment]
Does it work if you open the wallet manually?

**Comment by daeavelwyn** [comment]
@yan-  I forgot a step I thinnk in my tuto. You have to begin with removing .local/share/data/ownCloud before activating kwallet.
I edited my previous post to keep all informations together.

**Comment by MadEgg** [comment]
Same here. Definitely a timing issue. When I log in to KDE on Ubuntu Jessie with KDE 4.14, I get an error from OwnCloud stating that I need to re-enter my login credentials. I don't even get a kwallet popup asking me for my password.

When I close OwnCloud (without entering a password or doing anything else), and then restart it, I get a KWallet popup asking me for my password. If I enter the correct password, OwnCloud will start up and log into my accounts properly.

For me it's not acceptable to remove my KWallet password as that kindof defeats the purpose of KWallet in the first place.

This is all using OwnCloud Linux Desktop Client version 2.1 by the way.

**Comment by rpedrica** [comment]
I have a slight variation on this issue:

Slackware-current ( 14.2beta2 )
KDE/Plasma5
oc client 2.1.0

On initial installation, owncloud client asks for username and password which is then stored in a folder in kwallet. All working fine.

When I re-login to Plasma, then owncloud ( which was running at previous shutdown/restart ) starts and I get a prompt from KWallet to input my wallet password. I enter password and owncloud finishes startup but just sits there without connection to server and shows "Configuration error" on icon.

Here is my log on startup:

02-10 18:22:39:042 14701 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
02-10 18:22:39:059 14701 OCC::AbstractNetworkJob::setTimeout: void OCC::AbstractNetworkJob::setTimeout(qint64) 27000
02-10 18:22:39:060 14701 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
02-10 18:22:39:060 14701 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://*.*.co.za" + "status.php"
02-10 18:22:39:803 14701 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, ""))("installed", QVariant(bool, true))("maintenance", QVariant(bool, false))("version", QVariant(QString, "8.1.5.2"))("versionstring", QVariant(QString, "8.1.5")))   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0xed2a40)
02-10 18:22:39:804 14701 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:  QUrl("https://*.*.co.za/status.php")  with version  "8.1.5" ( "8.1.5.2" )
02-10 18:22:39:805 14701 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Undefined" -> "Credentials Wrong"
02-10 18:22:39:805 14701 OCC::AccountState::setState: AccountState state change:  "Disconnected" -> "Configuration error"
02-10 18:22:39:808 14701 OCC::FolderMan::slotAccountStateChanged: Account "rpedrica@cloud.emailstor.co.za" disconnected, terminating or descheduling sync folders
02-10 18:22:39:813 14701 unknown: QObject::connect: No such slot QKeychain::ReadPasswordJobPrivate::kwalletReadFinished(QDBusPendingCallWatcher*)
02-10 18:22:42:396 14701 OCC::PassiveUpdateNotifier::backgroundCheckForUpdate: virtual void OCC::PassiveUpdateNotifier::backgroundCheckForUpdate()
02-10 18:22:42:397 14701 OCC::OCUpdater::backgroundCheckForUpdate: virtual void OCC::OCUpdater::backgroundCheckForUpdate() checking for available update
02-10 18:22:42:397 14701 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
02-10 18:22:43:473 14701 OCC::PassiveUpdateNotifier::versionInfoArrived: Client is on latest version!

I then have to go into KWalletmanager and remove the owncloud folder, restart owncloud, go to account and sign in: it asks me for my owncloud server password now. A new owncloud folder appears in kwalletmanager and oc now works again until the next oc close or machine restart.

This issue only started when I upgraded to 2.1.0 - 1.8.4 and prior was fine. I compile my own oc clients.

Regards, Robby

**Comment by guruz** [comment]
``` 02-10 18:22:39:813 14701 unknown: QObject::connect: No such slot QKeychain::ReadPasswordJobPrivate::kwalletReadFinished(QDBusPendingCallWatcher*)```

> I compile my own oc clients.

Make sure to also be on the latest greatest qtkeychain.
https://github.com/frankosterfeld/qtkeychain

**Comment by rpedrica** [comment]
@guruz, I'm on 0.50 which is the latest.

**Comment by bidinou** [comment]
This will hopefully be automagically fixed soon as the well known LTS distro will be soon released, with KDE 5.

In my case (former LTS with latest KDE 4.x) I put a blank password in kwallet and a big startup delay and I still have the issue now and then (probably because I have a very old PC that takes a lot of time to start :)

**Comment by sergiocallegari** [comment]
The LTS distro has been released and the issue has actually worsened for me:

with Kubuntu 15.10, the only issue was the too quick timeout of kwallet.  Now owncloud asks for the password at the same time when kwallet asks for its password.

**Comment by sergiocallegari** [comment]
To summarize:

1. In the recently released Kubuntu 16.04 that uses qtkeychain 0.5 the problem persists.

2. Trying to add kwalletd or kwallted5 to the autostarted programs does not seem to make any difference

3. I think that looking into the problem is made more complex by the fact that there are at least two ways in which KDE can automatically start the owncloud client at login:

  - as an automatically started program. This is what happens when one ticks "launch on system startup" in the owncloud client configuration dialog (general tab). I believe that in this case the owncloud client is added to the KDE automatically started applications, visible from the System Settings -> Startup and Shutdown -> Autostart tab.

  - as a part of an automatic session restore.  This happens if one has "restore previous session" ticked in System Settings -> Startup and Shutdown -> Desktop sessions

Since owncloud includes its own "launch on system startup" option, I think it should exclude itself from the applications that are considered part of the saved session and restored automatically

**Comment by eehmke** [comment]
The issue is still valid. Perhaps I can shed some light on it.
I upgraded my system from Linux Mint 17.3 to 18. I kept my home partition and reinstalled the system. In that process, the new kwalletmanager5 was left without a master password. It kept working and provided the passwords for the applications, namely kmail and owncloud. This worked flawless, owncloud was started with KDE and got initialized with correct password.

Next I configured kwalletmanager5 and set a master password to it again. Soon at the next system restart the trouble began: kmail requested its passwords, kwallet popped up and requested the master password, in the meantime owncloud requested its password, did not get it immediately, and popped up its own password request dialog. When I then cancel the owncloud password dialog, call the owncloud menu and select "Log in", it works and gets its password from kwallet.

**Comment by Agustin-Pantoja** [comment]
Have the same problem. I use ubuntu in one laptop and kubuntu in the other one. Zero problems with owncloud in ubuntu, not asking for loging everytime.
In kubuntu I have disabled kwallet and owncloud ask for password everytime I restart the laptop. 
Not sure how to solve it, but I am right sure that I do not want to enable kwallet. Any help here would be much appreciated.

**Comment by guruz** [comment]
@Agustin-Pantoja You need to run something that qtkeychain supports, else the ownCloud client can't store its password.
https://github.com/frankosterfeld/qtkeychain
