### ISSUE TITLE
Recent Changes menu item stops working after sleep on Mac OSX

### ISSUE THREAD

**Issue by tessus** [owncloud/client#2236]
When I start ownCloud the **Recent Changes** menu item has a sub menu that shows the most recent changes.

When I close my MacBook and re-open it, the **Recent Changes** menu item is not working anymore. No matter how many sync operations are done, the item never shows a sub menu again.
Clicking on the **Recent Changes** menu item does not do anything either.

![screen shot 2014-09-22 at 15 54 25](https://cloud.githubusercontent.com/assets/223439/4363186/4d58a788-4293-11e4-9853-0869e2e40354.png)

MacOSX 10.9.x
ownCloud Sync 1.6.3 (build 878), but this problem also occuured with 1.6.1 and 1.6.2

**Comment by guruz** [comment]
Works for me with 1.8
Please re-test

**Comment by tessus** [comment]
@guruz the original problem has been solved, but as mentioned in my previous comment, the problem has shifted:

After coming out of hibernation the menu entry is still there, but it has only 2 entries: `None.` and `Details...`:

![screen shot 2014-11-22 at 3 07 03](https://cloud.githubusercontent.com/assets/223439/5153403/0f3d26c2-71f5-11e4-90d1-703f54afaf0c.png)

But after only one sync action (delete on file, add one file), the Recent Changes menu has all the entries that were there before hibernation.

**Comment by guruz** [comment]
@tessus Do you want to retry this with 1.8.1rc2?
https://owncloud.org/install/#testing

There was a possible related issue with the state of the sync engine not being cleared up properly that is fixed now (137bce6dd0d93599692571cdd29261b3ce0aeaa2)

**Comment by tessus** [comment]
@guruz thx, I'll give it a try and let you know by tomorrow.

**Comment by tessus** [comment]
@guruz just tested 1.8.1rc2. unfortunately I still see the same issue https://github.com/owncloud/client/issues/2236#issuecomment-86992487
As an info: I'm still running MacOSX 10.9.5

**Comment by Dianafg76** [comment]
I'm just tested v1.8.1 (build 2356), and everithing is ok. I close the issue

**Comment by tessus** [comment]
@Dianafg76 Are you sure you are referring to the issue in https://github.com/owncloud/client/issues/2236#issuecomment-86992487 or to the problem the bug was opened for?
I have seen nothing in the code changes since 1.8.1 build 2335 (@ee7102) that would address this problem.
