### ISSUE TITLE
Desktop icon opens settings window

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#2374]
### Expected behavior
Double click in desktop icon and opens the settings window.

### Actual behavior
Double click in desktop icon..... nothing (the client is running and is shown in the taskbar)

### Steps to reproduce
Really? :smile: 
1. Double click the desktop icon 

@dragotin

**Comment by ogoffart** [comment]
Probably fixed by  3169833cd78335d23d2b5f08d8a0ca852998e070

**Comment by lmaestro** [comment]
I have tested in version 1.8.0-nightly20150218(build 4740) and it is not fixed.

**Comment by ogoffart** [comment]
Normaly, QtSingleApplication should emit messageRecieved which is connected to Application::slotParseOptions which should then open the settings.
But this does not work on windows. Perhaps QtSingleApplication is different on windows?

**Comment by lmaestro** [comment]
Fixed in version 1.8.0-nightly20150220(build 4749)

**Comment by cdamken** [comment]
### Great! 

Tested with ownCloud-1.8.0.4796-nightly20150302-setup.exe
