### ISSUE TITLE
Shell Integration win32: Support multiple ownCloud Client / branded client instances

### ISSUE THREAD

**Issue by danimo** [owncloud/client#2388]
Currently, if you run the ownCloud Client and a branded version at the same time, explorer will only show the icon of whatever app started first. The explorer integration should connect to both instead, with a mechanism which allows the clients to register their socket paths.

**Comment by guruz** [comment]
This is fixed for OS X thanks to @jturcotte ..

**Comment by ogoffart** [comment]
@dschmidt   is this still a problem?

**Comment by jnweiger** [comment]
## Tested on windows 10

Still an issue: Testpilotcloud 2.6.0 beta brings its shell integration.
When installing owncloud-2.70-daily, its shell integration is active after the first reboot, but then shell integration of the testilotcloud client is lost.
