### ISSUE TITLE
[Windows] Conflicts files sometimes created when saving Office file (without concurent modificiation)

### ISSUE THREAD

**Issue by ErwanVDX** [owncloud/client#3901]
### Steps to reproduce
This is the easyet way I found to reproduce the issue, but happened with other file format and timing.
1. Open MS Word, create a new file and save it in an owncloud folder.
2. Open the file, modify it, and then save it.
3. Close MS Word.

### Expected behaviour
The file should be synchronized on the server.

### Actual behaviour
The file is not synchronized on the server and a conflict file is created which stores the modifications done in step 2.
The occurence of the issue is low for almost every users of the owncloud instance, it is high for one of them (can't find out what differs, I think it's the frequency of Ctrl+S that is more important...).

### Server configuration
**Operating system**:
CentOS 7.1

**Web server:**
Apache 2.4.6

**Database:**
MariaDB 5.5

**PHP version:**
PHP 5.4.16

**ownCloud version:** (see ownCloud admin page)
8.0.7 (from EPEL repository)

**Updated from an older ownCloud or fresh install:**
Updated with the yum package manager, don't known the initial version (installed with the package manager on July, 2015), but I had this issue also with the version 8.0.5.

**List of activated apps:**

Enabled:
 - files
 - files_external
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - templateeditor
Disabled:
 - activity
 - external
 - files_encryption
 - files_locking
 - files_mv
 - gallery
 - provisioning_api
 - storagecharts2
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

$CONFIG = array (
  'log_type' => 'owncloud',
  'datadirectory' => '/home/owncloud/data',
  'updatechecker' => false,
  'check_for_working_htaccess' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/share/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/lib/owncloud/apps',
      'url' => '/apps-appstore',
      'writable' => true,
    ),
  ),
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxxx',
  'trusted_domains' => 
  array (
    0 => 'xxx.xxx.xxx',
    1 => 'xx.xx.xx.xx',
  ),
  'overwrite.cli.url' => 'http://xxx.xxx.xxx/xxx',
  'dbtype' => 'mysql',
  'version' => '8.0.7.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxx',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Network setup**
The owncloud server is accessed through a VPN (OpenVPN).

### Client configuration

**Operating system:**
Windows 7

** Client version ** 
2.0.1 (build 5446)

#### Client log
24/09/2015 17:29:22Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mppVDX                        Non autorisé à envoyer ce fichier car il est en lecture seule sur le serveur. Restauration135 ko    

A conflict file is produced each time the message "Non autorisé à envoyer ce fichier car il est en lecture seule sur le serveur. Restauration" is displayed (translation for "Not allowed to upload this file because it is read-only on the server, restoring").
I've seen some messages in the activity tab saying that a stat command on some files failed but they disapear from the display when the error message is displayed.

#### Client log
I extracted lines where the file is referenced

09-24 17:29:08:377 0x8bdef8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp")
09-24 17:29:08:382 0x8bdef8 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/"
09-24 17:29:08:434 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:08:435 0x8bdef8 OCC::SocketApi::fileStatus: OCC::SyncFileStatus OCC::SocketApi::fileStatus(OCC::Folder*, const QString&, c_strlist_t*) Could not determine state for file "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" will set STATUS_NEW
09-24 17:29:08:435 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:NEW:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:10:456 0xbf83c68 csync_walker: file: C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp [inode=133036 size=134656]
09-24 17:29:10:456 0xbf83c68 _csync_detect_update: file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp, instruction: INSTRUCTION_NEW <<=
09-24 17:29:10:764 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:10:765 0x8bdef8 OCC::SocketApi::fileStatus: OCC::SyncFileStatus OCC::SocketApi::fileStatus(OCC::Folder*, const QString&, c_strlist_t*) Could not determine state for file "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" will set STATUS_NEW
09-24 17:29:10:766 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:NEW:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:11:598 0x8bdef8 _csync_merge_algorithm_visitor: INSTRUCTION_NEW      client file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:11:683 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:11:735 0x8bdef8 OCC::AbstractNetworkJob::start: !!! OCC::PUTFileJob created for "http://vpn.VDX.com/owncloud" + "/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:12:095 0x8bdef8 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "http://vpn.VDX.com/owncloud/remote.php/webdav/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" )  FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created")
09-24 17:29:12:100 0x8bdef8 OCC::SyncJournalFileRecord::SyncJournalFileRecord: OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" Retrieved inode  133036 (previous item inode:  133036 )
09-24 17:29:12:102 0x8bdef8 OCC::SyncJournalDb::setFileRecord: "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14);" -7244578179408404302 104 "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" 133036 0 "1443107496" "0" "6405a265d168125ceefa146a2826cb92" "00008032ocd72b0fe1a8" "" 134656 0
09-24 17:29:12:105 0x8bdef8 OCC::SyncJournalDb::setUploadInfo: "DELETE FROM uploadinfo WHERE path=?1" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:12:109 0x8bdef8 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" INSTRUCTION_NEW 4 ""
09-24 17:29:12:112 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:12:281 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:12:283 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:13:752 0x8bdef8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp")
09-24 17:29:13:755 0x8bdef8 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/"
09-24 17:29:13:895 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:13:897 0x8bdef8 csync_vio_local_stat: CreateFileW failed on C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:13:898 0x8bdef8 OCC::FileSystem::getModTime: Could not get modification time for "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" with csync, using QFileInfo
09-24 17:29:13:898 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:15:838 0xbf83948 csync_vio_local_stat: CreateFileW failed on C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:15:838 0xbf83948 csync_ftw: Uniq ID from Database: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp -> 6405a265d168125ceefa146a2826cb92
09-24 17:29:15:838 0xbf83948 _csync_detect_update: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp excluded  (7)
09-24 17:29:15:838 0xbf83948 _csync_detect_update: file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp, instruction: INSTRUCTION_IGNORE <<=
09-24 17:29:16:143 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:16:145 0x8bdef8 csync_vio_local_stat: CreateFileW failed on C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:16:146 0x8bdef8 OCC::FileSystem::getModTime: Could not get modification time for "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" with csync, using QFileInfo
09-24 17:29:16:147 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:16:881 0xbf83948 csync_walker: file: owncloud://vpn.VDX.com/owncloud/remote.php/webdav/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp [file_id=00008032ocd72b0fe1a8 size=134656]
09-24 17:29:16:883 0xbf83948 _csync_detect_update: Need to update metadata for: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:16:883 0xbf83948 _csync_detect_update: file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp, instruction: INSTRUCTION_NONE <<=
09-24 17:29:16:968 0x8bdef8 _csync_merge_algorithm_visitor: INSTRUCTION_IGNORE   client file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:17:029 0x8bdef8 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     server file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:17:053 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:17:119 0x8bdef8 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" INSTRUCTION_IGNORE 6 "Stat échoué."
09-24 17:29:17:120 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:17:327 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:17:329 0x8bdef8 csync_vio_local_stat: CreateFileW failed on C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:17:329 0x8bdef8 OCC::FileSystem::getModTime: Could not get modification time for "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" with csync, using QFileInfo
09-24 17:29:17:330 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:19:618 0x8bdef8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp")
09-24 17:29:19:629 0x8bdef8 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/"
09-24 17:29:19:789 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:19:790 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:21:693 0xbf83768 csync_ftw: Uniq ID from Database: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp -> 6405a265d168125ceefa146a2826cb92
09-24 17:29:21:693 0xbf83768 csync_walker: file: C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp [inode=133036 size=134656]
09-24 17:29:21:694 0xbf83768 _csync_detect_update: file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp, instruction: INSTRUCTION_EVAL <<=
09-24 17:29:21:992 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:21:994 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:22:228 0x8bdef8 _csync_merge_algorithm_visitor: INSTRUCTION_SYNC     client file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:22:290 0x8bdef8 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     server file: Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp
09-24 17:29:22:316 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:22:320 0x8bdef8 OCC::SyncEngine::checkForPermission: checkForPermission: RESTORING "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:366 0x8bdef8 OCC::PropagateDownloadFileQNAM::start: virtual void OCC::PropagateDownloadFileQNAM::start() "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" 0
09-24 17:29:22:367 0x8bdef8 OCC::OwncloudPropagator::localFileNameClash: CaseClashCheck for  "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:369 0x8bdef8 OCC::SyncJournalDb::setDownloadInfo: "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/.Planification ABCDEF.mpp.~669a" "6405a265d168125ceefa146a2826cb92" 0
09-24 17:29:22:371 0x8bdef8 OCC::AbstractNetworkJob::start: !!! OCC::GETFileJob created for "http://vpn.VDX.com/owncloud" + "/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:372 0x8bdef8 OCC::FolderWatcher::pathIsIgnored: * Discarded as is hidden! "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/.Planification ABCDEF.mpp.~669a"
09-24 17:29:22:602 0x8bdef8 OCC::PropagateDownloadFileQNAM::slotGetFinished: void OCC::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "http://vpn.VDX.com/owncloud/remote.php/webdav/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" )  FINISHED WITH STATUS 0 "" 0 134656 134656 0 "" "134656"
09-24 17:29:22:606 0x8bdef8 OCC::OwncloudPropagator::localFileNameClash: CaseClashCheck for  "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:612 0x8bdef8 OCC::PropagateDownloadFileQNAM::downloadFinished: Created conflict file "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" -> "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF_conflict-20150924-171136.mpp"
09-24 17:29:22:623 0x8bdef8 OCC::SyncJournalFileRecord::SyncJournalFileRecord: OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" Retrieved inode  78567 (previous item inode:  133036 )
09-24 17:29:22:626 0x8bdef8 OCC::SyncJournalDb::setFileRecord: "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14);" -7244578179408404302 104 "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" 78567 0 "1443107496" "0" "6405a265d168125ceefa146a2826cb92" "00008032ocd72b0fe1a8" "RDNVCK" 134656 0
09-24 17:29:22:629 0x8bdef8 OCC::SyncJournalDb::setDownloadInfo: "DELETE FROM downloadinfo WHERE path=?1" "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:633 0x8bdef8 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp" INSTRUCTION_CONFLICT 7 "Non autorisé à envoyer ce fichier car il est en lecture seule sur le serveur. Restauration"
09-24 17:29:22:635 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:22:638 0x8bdef8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp")
09-24 17:29:22:638 0x8bdef8 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) Sync running, IGNORE event for  "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:642 0x8bdef8 OCC::FolderWatcher::pathIsIgnored: * Discarded by component ignore pattern  ".Planification ABCDEF.mpp.~669a"
09-24 17:29:22:645 0x8bdef8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp")
09-24 17:29:22:645 0x8bdef8 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) Sync running, IGNORE event for  "C:/Users/xxx/VDX/Projets GLSI/PR.ABCDEF.001.001/02. Exigences/Planification ABCDEF.mpp"
09-24 17:29:22:752 0x8bdef8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"
09-24 17:29:22:753 0x8bdef8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\xxx\VDX\Projets GLSI\PR.ABCDEF.001.001\02. Exigences\Planification ABCDEF.mpp"

#### ownCloud log (data/owncloud.log)
Time not related to other logs (was desactivated when the issue was reproduced), not sure errors are revelant.

Error	core	unable to rename, file does not exists : files_versions/Dossier personnel/Nouveau dossier.v	2015-09-29T07:50:02+00:00
Error	PHP	Undefined index: extension at /usr/share/owncloud/apps/files_versions/lib/storage.php#320	2015-09-29T07:50:02+00:00
Error	core	unable to rename, file does not exists : files_versions/Test.v	2015-09-29T07:27:59+00:00
Error	PHP	Undefined index: extension at /usr/share/owncloud/apps/files_versions/lib/storage.php#320	2015-09-29T07:27:59+00:00
Error	core	unable to rename, file does not exists : files_versions/Dossier personnel/Nouveau dossier.v	2015-09-29T07:21:23+00:00
Error	PHP	Undefined index: extension at /usr/share/owncloud/apps/files_versions/lib/storage.php#320	2015-09-29T07:21:23+00:00

**Comment by rperezb** [comment]
@Dianafg76 can you please check whether you reproduce this bug,

thx

**Comment by Dianafg76** [comment]
I can't reproduce this issue. 
I have checked with:  Desktop vownCloud-2.0.2.5504-nightly20151001-setup.exe 
Server version {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

Tested with a file stored on the root
Tested with a file stored on a folder

Can you please provide to us further details? Such as:

What it has called my attention is this server error:
```
Error core unable to rename, file does not exists : files_versions/Dossier personnel/Nouveau dossier.v 2015-09-29T07:50:02+00:00
```

Perhaps this may be related to any server side issue, @PVince81 does this make you ring any bell related to 8.0.7?

I am currently checking againts 8.0.8

**Comment by Dianafg76** [comment]
I am currently checking againts 8.0.8: and it works ok

**Comment by Dianafg76** [comment]
can you upgrade your server to version 8.0.8
Thanks

**Comment by Zarus42** [comment]
Thank you, I'll upgrage the server to the version 8.0.8 and try to produce more logs of this error.
May be long as the issue seems to appears periodically (several false conflicts at a time and then nothing wrong for several days).

I found this issue that seems to describe the same error : https://github.com/owncloud/client/issues/2577
As I see the issue is closed but the bug is in fact not resolved.

Could the issue be caused by a particular network setup ?

**Comment by PVince81** [comment]
Regarding the version without timestamp, there was an old similar issue, see https://github.com/owncloud/core/issues/17962 (should be fixed already)

**Comment by Zarus42** [comment]
The bug occured again with the user that is the most affected (with owncloud 8.0.7), but there are no errors in the server log this time. Any clue where I should look ?

P.S.: I have just upgraded my production environment to 8.0.8.

**Comment by ErwanVDX** [comment]
The issue still persists using the version 8.0.8.
I collect some information.

On the owncloud client, there is always the error:
`Non autorisé à envoyer ce fichier car il est en lecture seule sur le serveur. Restauration`
which is the translation for:
`Not allowed to upload this file because it is read-only on the server, restoring`

The conflict file always has last modifications in it (users don't loose any data).
Sometimes, the initial file is empty (0 Kb); it shouldn't.

![screen_conflit_document](https://cloud.githubusercontent.com/assets/14839265/10509257/1110c8da-732c-11e5-8224-22d96b2714fc.png)

Here is the server log in debug log level on a period where the issue occured for the client having the IP 10.8.0.22:

```
{"reqId":"d4cdfd511a5082fae5541bca9aaa7d14","remoteAddr":"10.8.0.22","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/usr\\\/share\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/usr\\\/share\\\/owncloud\\\/remote.php(54): require_once('\\\/usr\\\/share\\\/ownc...')\\n#9 {main}\",\"File\":\"\\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-10-14T13:56:15+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"01ac07b558ba366e6091980ebc65fd2e","remoteAddr":"10.8.0.6","app":"files_versions","message":"Mark to expire \/Dossier personnel\/TODO.txt next version should be 1444813557 or smaller. (prevTimestamp: 1444817157; step: 3600","level":0,"time":"2015-10-14T13:57:11+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/Dossier%20personnel\/TODO.txt"}
{"reqId":"01ac07b558ba366e6091980ebc65fd2e","remoteAddr":"10.8.0.6","app":"files_versions","message":"Mark to expire \/Dossier personnel\/TODO.txt next version should be 1444651518 or smaller. (prevTimestamp: 1444737918; step: 86400","level":0,"time":"2015-10-14T13:57:11+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/Dossier%20personnel\/TODO.txt"}
{"reqId":"01ac07b558ba366e6091980ebc65fd2e","remoteAddr":"10.8.0.6","app":"files_versions","message":"Expire: \/Dossier personnel\/TODO.txt.v1444816639","level":0,"time":"2015-10-14T13:57:11+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/Dossier%20personnel\/TODO.txt"}
{"reqId":"01ac07b558ba366e6091980ebc65fd2e","remoteAddr":"10.8.0.6","app":"files_versions","message":"Expire: \/Dossier personnel\/TODO.txt.v1444728045","level":0,"time":"2015-10-14T13:57:11+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/Dossier%20personnel\/TODO.txt"}
{"reqId":"79ba31fad1f1cb4313b5001616e738fa","remoteAddr":"10.8.0.22","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/usr\\\/share\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/usr\\\/share\\\/owncloud\\\/remote.php(54): require_once('\\\/usr\\\/share\\\/ownc...')\\n#9 {main}\",\"File\":\"\\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-10-14T14:02:36+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"c8c9b746f142016fc662c51f6408ab79","remoteAddr":"10.8.0.6","app":"core","message":"OC\\Tags::__construct, tags: Array\n(\n)\n","level":0,"time":"2015-10-14T14:15:40+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/list.php?dir=%2F&sort=name&sortdirection=asc"}
{"reqId":"051371409cd40f18d1ef743cb15a0bd1","remoteAddr":"10.8.0.22","app":"core","message":"OC\\Tags::__construct, tags: Array\n(\n)\n","level":0,"time":"2015-10-14T14:44:57+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/list.php?dir=%2F&sort=name&sortdirection=asc"}
{"reqId":"c2399d63d7a38cc24717f325f18262e2","remoteAddr":"10.8.0.22","app":"files_trashbin","message":"remove \"synoptique.pdf\" from trash bin because it is older than 30","level":1,"time":"2015-10-14T14:47:48+00:00","method":"DELETE","url":"\/owncloud\/remote.php\/webdav\/TRAVAIL_COURANT\/Test.doc"}
{"reqId":"fb4bcc2ba4ce1e1d8cbe5a04ee512078","remoteAddr":"10.8.0.38","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/usr\\\/share\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/usr\\\/share\\\/owncloud\\\/remote.php(54): require_once('\\\/usr\\\/share\\\/ownc...')\\n#9 {main}\",\"File\":\"\\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-10-14T15:06:39+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"2990f50ae3b2c38666380ea01cbcdfda","remoteAddr":"10.8.0.22","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/usr\\\/share\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/usr\\\/share\\\/owncloud\\\/remote.php(54): require_once('\\\/usr\\\/share\\\/ownc...')\\n#9 {main}\",\"File\":\"\\\/usr\\\/share\\\/php\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-10-14T15:55:23+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```

**Comment by Flexxxo** [comment]
Unfortunately I am experiencing the same issue. It began for me with 7.0.4 and I was hoping (based on this: https://github.com/owncloud/core/issues/12991) that 7.0.10 would solve it. It didn't and as it also seems to exist with 8.0.8 in some cases, I really hope for a fix.

I experience this problem particularly with MS Word and Excel files. Opening existing files in the local repository, changing & saving them results in the Windows OC client reporting that the file cannot be uploaded as it is read-only on the server. Using the workaround from 12991: delete locally, wait until it is deleted online, then change the -conflict file name to the original file name and upload succeeds. -conflict is always the latest version. Also here non-conflict versions sometimes get 0 bytes size.

Is there anything I could to to help? If you need any log files please instruct me on how to generate them or where to find them. Thanks!

**Comment by raimund-schluessler** [comment]
I see a similar error which I reported in https://github.com/owncloud/client/issues/4023

For me this occurs since I updated to client v2.0.0. I found out that the error is gone when I allow to synchronize hidden files (this config option was introduced/enabled in 2.0.0).

@Flexxxo @ErwanVDX 
Could you please check whether the error disappears when you check "Sync hidden files" in the ignored files section?

**Comment by Flexxxo** [comment]
Thanks for your input raimund - I changed the option and will now observe it and then i'll report back. Keeping my fingers crossed.

**Comment by Flexxxo** [comment]
First result: Working with doc and xls files today did not come up with the (well known) messages in the Windows client's log that the file "is read-only on the server". Log is quite clean and for the first time I see this: "Local file changed during sync". So far I hope this could have been the key but i'll continue to observe it.

**Comment by Flexxxo** [comment]
Unfortunately my problems are not solved. Opening an existing Word document (.doc), editing and saving it using another file name most of the time results in a 0 byte file with the correct name and an additional -conflict file with the correct/real content. :-(

The well-known message that the file is read-only on the server appears in the client activity protocol.

Sync hidden files is activated and the version of the Windows client is 2.1.0-nightly20151102 (build 5597).

**Comment by ErwanVDX** [comment]
The issue still occurs for me too with "Sync hidden files" checked, client version 2.0.2.

**Comment by Flexxxo** [comment]
No improvement with Version 2.1.0-nightly20151117 (build 5630) - no matter if sync hidden files is on or off.

![oc](https://cloud.githubusercontent.com/assets/15352119/11273335/08a34e26-8ed3-11e5-8480-2887a23e36ad.png)

**Comment by guruz** [comment]
Current client version is 2.1, current server version is 8.2.2
Could you try that?

**Comment by ErwanVDX** [comment]
I'll try with client version 2.1, it is awkward to update my server right now.

However the error did not appear for more than one month (nothing changed in my setup... except maybe some network setup). So it will be hard for me to know if the issue is realy fixed.

**Comment by Flexxxo** [comment]
Unfortuntely I cannot update the server now because I had severe problems with OC versions higher than the 7.0.10 I'm using at the moment.

Clients didn't solve it. Have been using numerous nightly builds since November, at the moment all Windows clients use the nightly from January, 4th 2016 but problem persists. Still cleaning up the conflict files manually.

Happens most of the time in MS Word for me.

**Comment by ogoffart** [comment]
`Not allowed to upload this file because it is read-only on the server, restoring`

This happens because the server reports that the files are read only, as the error message says.  This is an expected behavior.

There is a known bug on earlier server version which once the folder are set in read-only mode, they do not notify us that their are back in a non-read only mode if the rights are changed. https://github.com/owncloud/core/issues/16587
Is that the case?

**Comment by ErwanVDX** [comment]
Please could you explain why the issue has been closed ?

**Comment by guruz** [comment]
No one came up with more info after @ogoffart asked and you should try with a recent server version and client 2.1.1 rc2 :) thanks

**Comment by ErwanVDX** [comment]
I'm not able to say if it's related to the issue owncloud/core#16587 (from a user point of view I don't think). But ok, I'll come back if the issue still occurs when I could upgrade my production environment.

Thank you everybody !

**Comment by Flexxxo** [comment]
I'm with ErwanVDX here. I have been using the latest nightly builds of the Windows client in the last weeks. Update twice a week. Did not solve the problem.

Unfortunately I had tried the upgrade to OC 8 twice in the past and this delivered a bunch of problems on my hosted webspace. So I wanted to avoid to upgrade the server part to 8.x although I understand that this could probably solve the problem.

**Comment by Flexxxo** [comment]
Ok. Today I updated to 8.2.2 and client is 2.1.1 build 5837.

Still the described conflict-files problem when using Word and Excel. :(

**Comment by dragotin** [comment]
@Flexxxo can you verify the steps to reproduce, are they accurate for you? Also, it would be helpful if you could create a logfile which shows this problem with one file. Thanks!

**Comment by Flexxxo** [comment]
I'll do my best to reproduce. Where to find the settings for the logfiles? Are they enabled by default?

**Comment by ogoffart** [comment]
start the client with the --logile  command line option

**Comment by Flexxxo** [comment]
Thank you, Olivier.

My problem - at the moment - is, that the created log is very comprehensive including file and folder names of private and business data and much more info than just about the test files I am creating to reproduce the problem. At the moment I don't want to share such an amount of data.

But basically I want to support and **confirm** the original problem description ErwanVDX posted when opening this thread:
_1. Open MS Word, create a new file and save it in an owncloud folder.
2. Open the file, modify it, and then save it.
3. Close MS Word.
_
This is exactly what happens here. It happened with all subversions of OC7 and is happen until now with OC 8.2.2 and also with all clients (Windows) in the last months including stable and nightly builds.

Opening an existing Word document (applies for Excel, too), modifying and re-saving it leads to a conflict file and a 0 byte file with the correct file name without the conflict extension. And also leads to the already mentioned entry in the client software that this file "cannot be uploaded because it is read-only on the server".

**Comment by Flexxxo** [comment]
Funny detail: with the latest stable build 5837 this conflict situation with the Word doc files leads to crashes of the Windows client! I will always send the error reports.

**Comment by ogoffart** [comment]
I do not have MS Word to try to reproduce. I tried to reproduce with other programs without success.  
Can you please provide a log?

Note that if the file are read only on the server, this is the expected behavior.  If the server reports that the file is read only, we restore it.

**Comment by dragotin** [comment]
This is probably caused by https://github.com/owncloud/core/issues/16587 . Please evaluate with the later server version and reopen if the problem persists. For more investigation we need a logfile.

**Comment by guruz** [comment]
Does it behave differently with doc vs docx?
https://github.com/owncloud/client/issues/4624#issuecomment-204007521
Just wondering..

**Comment by Flexxxo** [comment]
"Please evaluate with the later server version"

Ok, as I said, I updated to 8.2.2 recently. I do not intend to upgrade to v9 within the next weeks.

@guruz: For me it applies for .DOC files as I do not use .DOCX at all. All of my documents are good old DOC files.

**Comment by ErwanVDX** [comment]
@guruz My users had this issue with .doc files too, they are not using the docx format.
However I cannot confirm it doesn't happens with docx files as I cannot reproduce the issue as wanted...
