### ISSUE TITLE
Files downloaded without any change

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/client#4001]
Using 2.0.2 and after a restart of my computer, the sync client started to download all the files again.
oC server version 8.1.1. I also got "Connetion closed" on some files. Logs will be attached here.

Sync client log:
https://gist.github.com/fossxplorer/2698442b608cdce9243a

**Comment by ogoffart** [comment]
So for the file that are downloaded, we see something like:

```
10-26 09:50:44:227 0x307f318 _csync_detect_update: Database entry found, compare: 1438336129 <-> 1438336129, etag: 29531e17bce5d34c9f25b643c713fb7f <-> 55bb44819f375, inode: 0 <-> 613258173, size: 5914 <-> 5914, perms: RDNVW <-> RDNVW, ignore: 0
10-26 09:50:44:228 0x307f318 _csync_detect_update: file: centos7_udev.png, instruction: INSTRUCTION_EVAL <<=
```

As we see, the etag are different : 29531e17bce5d34c9f25b643c713fb7f <-> 55bb44819f375.  The older etag was much shorter.

I need help from some server expert to know if there was a change in the size of the etag or what that could possibly mean. @PVince81

**Comment by PVince81** [comment]
I believe the older etag was shorter and at some point the format was changed and it got longer, but only when re-generated.
@icewind1991 might know.

@fossxplorer are you using any external storage ? A full report could help

**Comment by ogoffart** [comment]
maybe somebody else re-uploaded the files?   Maybe related to the daylight saving time change? (Recent client are fixed, but older client were re-uploading files for FAT32 file system.  Maybe some external storages on the server have the same problems)

**Comment by icewind1991** [comment]
Old etags always were a `uniqid`, now etags for files are an md5 of some meta data, folder still have the old etag length for now

**Comment by fossxplorer** [comment]
@PVince81 i'm using local storage through NFS share. No external storage involved or used with this user account on the server. I can provide more details if still needed.

@ogoffart absolutely nobody is acceding these folders or account other than me. I'm using XFS filesystem exported over NFS.

**Comment by PVince81** [comment]
@fossxplorer could be related to the DST change, maybe the mtime/time of the NFS didn't match the one of the OC server for a short time ?

**Comment by guruz** [comment]
Please check with 2.1
