### ISSUE TITLE
sync client silently fails to sync some files but does not raise visible error to user

### ISSUE THREAD

**Issue by fleish** [owncloud/client#4099]
I've been experiencing a strange issue with Owncloud sync client on Mac OSX. Users will report local copies of some files show up as encrypted garbage (starting with HBEGIN:cipher:AES-256-CFD:HEND-------) while the client shows the green check mark indicating the local copy of the owncloud data should be OK.

We are running owncloud 7.0.5 (stable) on the server and have seen this with various versions of the sync client from 1.8.x to the current version 2.0.2 (build 2818).

One thing that struct me as possibly relevant was this finding in the user's .owncloudsync.log file. During a fresh install and attempt to perform a full sync I saw many entries like this:
|0|Some Path/Some.File.Name.docx|INST_NEW|Down|1446062560|563129e506e1f|110719|00756422oce1f3d9f516|0||0|0|0|||INST_NONE|

And sure enough, that file was one of the problem files.

To see if the problem stuck, I quit owncloud, removed the account, re-added the account, and performed a fresh sync. This time the file was fine, so I checked the .owncloudsync.log file again and found this instead:
21:29:49|370|Some Path/Some.File.Name.docx|INST_NEW|Down|1446062560|563129e506e1f|110719|00756422oce1f3d9f516|4||0|0|0|||INST_NONE|

So the bad sync had no timestamp (field is null) and a status code of 0, while the good sync had a timestamp and a status code of 4.

I don't see anything in the server logfile during the timeframe of the bad sync. Does anyone have an idea what might be happening here and/or how to go about fixing it? Thanks in advance.

**Comment by tflidd** [comment]
There was one thing about encryption fixed in OC 7.0.6:
> Fix issue with broken encryption key when deleting file shared by other user

I have no idea if this is related and there are tons of other small fixes. The latest release of OC 7 is 7.0.11, perhaps this is already fixed.

**Comment by guruz** [comment]
Indeed, please update and/or check other support options.
https://owncloud.org/support/

**Comment by fleish** [comment]
@guruz can this be re-opened? I have updated to 7.0.11 and the issue still persists

**Comment by guruz** [comment]
CC @schiesbn

**Comment by PVince81** [comment]
@fleish OC 7 will only receive security fixes, so any potential fix would at most appear in 8.0. So you might want to try upgrading to 8.0 eventually.

I assume that you're not using external storage ? Are these shared files / is that user a recipient of the shares ?

Can you check `oc_filecache` and see whether the broken file's entry has its "encrypted" column set to 1 ?

The only other reason why the sync client might receive an encrypted file was due to an older session being used before encryption was enabled. But since you reset the sync client instance from scratch this cannot be the reason.

**Comment by fleish** [comment]
@pvince81 I hear you on OC7 vs. OC8. It's in my pipeline, but hasn't made it to the top of the stack yet.

I am not using external storage, just the local filesystem. These files are shared by the user to a group created in owncloud.

I have checked oc_filecache for one of the files that exhibits this behavior (appears to have data, but downloading results in a 0 byte file - downloading the previous version results in a proper file with data) and encrypted is set to 1. In my search for a file that exhibits this behavior, I found another file that exhibited similar behavior, the only difference being even the previous version file downloads as a 0 byte file. The row in oc_filecache for that filename also has encrypted set to 1.

Entries were checked like so:
mysql> select encrypted from oc_filecache where name like 'FILENAME';
+-----------+
| encrypted |
+-----------+
|         1 |
+-----------+
1 row in set (0.57 sec)

I don't know if it's relevant or not, but I widened the search with a wildcard at the end of the filename and found some entries where encrypted was set to 0 like this:
mysql> select * from oc_filecache where name like 'FILENAME.v%'\G
+-----------+
| encrypted |
+-----------+
|         0 |
+-----------+
1 row in set (0.57 sec)

When you say an older session being used before encryption was enabled - AFAIK we have always had encryption enabled on the server side.

**Comment by PVince81** [comment]
Okay, so you found some unencrypted versions. The server is supposed to be able to handle mixed encrypted versions and unencrypted versions, at least it should in OC 8.2.1. Not sure about older versions. @schiesbn ?

**Comment by fleish** [comment]
Any idea how/why there would be any unencrypted versions?

**Comment by fleish** [comment]
@Pvince81 Happy new year Vince & all. I wanted to check back if you had any thoughts on this issue. I'm still unsure how/why we would ever have any unencrypted versions considering we enabled encryption very early on if not from day 1.

Some additional data, the user who has repeatedly experienced this issue often renames directories (e.g. from DIR -> DIR_EDIT & then later from DIR_EDIT -> DIR_DONE). They most recently renamed a directory to notate it was now archived for 2015 which triggered a big sync that at first threw an error (not sure the exact error - trying to get it from the user) but then they said it re-sycned and seemed to work OK. 

{"app":"Encryption library","message":"No share key found for user \"**REDACTED-GUID1**\" for file \"__DIR\"","level":2,"time":"2016-01-06T17:04:21+00:00"}
{"app":"Encryption library","message":"No share key found for user \"**REDACTED-GUID2**\" for file \"__DIR\"","level":2,"time":"2016-01-06T17:04:21+00:00"}
{"app":"Encryption library","message":"No share key found for user \"**REDACTED-GUID3**\" for file \"__DIR\"","level":2,"time":"2016-01-06T17:04:21+00:00"}
{"app":"Encryption library","message":"No share key found for user \"**REDACTED-GUID4-OWNER**\" for file \"__DIR\"","level":2,"time":"2016-01-06T17:04:21+00:00"}

**Comment by fleish** [comment]
@PVince81 & @schiesbn this continues to plague one of my users on the regular. Any thoughts?

**Comment by PVince81** [comment]
The error that user got when renaming is likely to be the cause. I guess that maybe the move operation didn't finish properly and not all encryption keys were moved.

The last error messages you posted seem to show that some keys are missing. You might be able to repair this manually by looking at the "data/$user/files_encryption" directory and checking whether the missing encryption keys for that file are still in the old non-renamed folder. Then move these to the new folder where they are missing (all inside "files_encryption")

**Comment by fleish** [comment]
@pvince81 I think you're on to something there. I checked data/$user/files_encryption and found what I believe to be the keys for one of the directories in question - however it seems to still be named what it was named originally before several (attempted) rename operations, so it looks like this:

data/$user/files/Dir/Subdir1/Sub Dir 2/someimage.jpg
data/$user/files_encryption/Dir/Subdir1/OLD Sub dir 2 name/someimage.jpg.key

I tried to download a file out of this directory using the web interface and got the Encryption Key Not Found error in owncloud.log and Firefox can't find the file at https://owncloud.domain.org/index.php/apps/files/ajax/download.php?dir=/Dir/Subdir1/Sub Dir 2/Photos&files=someimage.jpg. in the browser

I then went into data/$user/files_encryption and tried to replicate the encryption keys to the new name of Sub dir 2 so it looks like this:

data/$user/files/Dir/Subdir1/Sub Dir 2/someimage.jpg
data/$user/files_encryption/Dir/Subdir1/OLD Sub dir 2 name/someimage.jpg.key
data/$user/files_encryption/Dir/Subdir2/Sub dir 2/someimage.jpg.key

This time when I tried to download the file using the web interface, I ended up @ this URL https://owncloud.domain.org/apps/files_encryption/files/error.php?p=0&errorCode=3 with this text displayed in the browser:  Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you. 

I was logged in as the owner of the files who has shared them with a group of which the owner is also a member.

**Comment by PVince81** [comment]
@fleish the ".key" file isn't enough. You also need the "shareKey" files for each user who has access to the file to make it work, even the owner. The owner should also have a "shareKey" with their name.

**Comment by fleish** [comment]
@PVince81 thanks for the extra pointer, that was the last piece of the puzzle and I was able to successfully decrypt the files in the directory after copying over the share key directory as well.

Now the only remaining question is how/why this happens and if there is anything that can be done to prevent it in the future?

**Comment by PVince81** [comment]
If you're still on ownCloud < 8.2, I suspect it could be either a timeout or a concurrency issue.
Since OC 8.2 there is a new locking mechanism to prevent concurrent access on files to mess up.

See https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/files_locking_transactional.html
(the redis version of it is also available on 8.1)

**Comment by fleish** [comment]
@PVince81  I'm still on 7.0.5 in production right now. My test box is running 7.0.11 and an apt-get download owncloud reveals the current 7.x release available is 7.0.12. Is there a recommended upgrade path? I have a note here that someone advised me to go from 7.0.11 -> 8.1.4 -> 8.2.1. I don't recall who recommended this, perhaps someone in IRC or another github issue. But figured I'd double-check since I had an issue jumping from 6.0.x -> 7.0.x previously that was resolved by restoring from backup and then doing a step-upgrade from 6.0.x-> 7.0RC1 or something. It was painful so I'd prefer to avoid that this time around.

In general, are there any tweaks on the server side I should consider if clients are timing out? Or is the new locking feature in 8.2 supposed to circumvent the need for managing it that way?

**Comment by PVince81** [comment]
No, when upgrading just do: 7.0.5->8.0.10->8.1.5->8.2.2.
Starting with 8.1, the second digit is considered a major update.

Regarding the timeout, I don't think locking will help preventing them.
You might need to tweak server settings like max allowed running time for a PHP process, etc.
I'm not very familiar with this part so you might want to check the docs or forums http://owncloud.org/support from people having similar issues.

**Comment by ogoffart** [comment]
This is in any case not a bug in the client.  So closing this issue.
