### ISSUE TITLE
Sync Wizard: please allow to select local directories before starting sync

### ISSUE THREAD

**Issue by schittli** [owncloud/client#4314]
Good evening
I probably have a very common use case for the Windows Client:
I would lke to sync some local directories to owncloud, for example:
- c:\data
- c:\portableapps
- c:\projects
- c:\ISOs
- c:\dev
- c:\Scripts

Therefore I do the following on the Windows Client:
- start new folder synchronisation wizard
- select local directory: c:\
- select target: ...\PC-Data\

At this point, it would be great if one could either:
- select "let me choose to select the folders to synchronize later"
  or
- directly select the local folders which should be synchronized

The actual Wizard starts to synchronize the complete C: Drive and afterwards, I can / have to remove all folders which I do not want so synchronize. 
It feels like it's the wrong way ;-)

I know I can create many folder synchronization settings - one for each folder -, which is a lot of work compared to just to select c:\ and then add the required folders.

Kind regards,
Tom

**Comment by JetUni** [comment]
This is something that I have wanted for a very long time and I'm surprised that owncloud still doesn't address this! Can we get more discussion on this and hear from the developers what's possible in this situation?

**Comment by phil-davis** [comment]
Note: At the moment the client considers the server to be "master" and contain a superset of whatever is on the client. So if you did allow the whole C: drive to sync up to the server, waited for the sync to finish, and then selected the folders for sync, you would find that the client would delete locally all the folders that you had chosen not to sync from the server. i.e. at the moment "what to sync" is "what to sync from the server", NOT "what to sync from the client". (there is plenty of discussion about this kind of stuff in other issues)

The design of this enhancement could let you select a number of folders to sync from the client, and setup a Folder Sync Connection for each one of them, mapping up to a (most likely new) folder of the same name on the server.

**Comment by phil-davis** [comment]
I have not been in discussions about this for a while now - struggling to quickly find the issues in GitHub, e.g. https://github.com/owncloud/client/issues/100

You will already have individual sync connections for Documents, Downloads, Photos, Videos, whatever, that go to different individual folders on the server. You can:

1) add a new sync connection for "home" and let it sync everything (the ugly bit)
2) when Documents, Downloads, Photos, Videos folders exist in "home" on the server, then do the selective sync and choose not to sync them from the server, AND to keep them on the client. That leaves these folders "dangling unsynced" on the client.
3) delete excess files in "home" Documents, Downloads, Photos, Videos on the server (just so as not to waste space), but leave the folders there.

That should work, but it is ugly.

**Comment by guruz** [comment]
I think this is already solved with the "Manual folder configuration" button and now in 2.5 easier discovered with the "Manually create sync folders or "Create sync folders later" option shown in PR https://github.com/owncloud/client/pull/6470

**Comment by guruz** [comment]
(If not please let us know..)

**Comment by JetUni** [comment]
This does not fix the issue at all. I waited all this time for the beta, but there is still no option to select local folders when adding a sync folder. What more information is needed to get this resolved properly?

**Comment by michaelstingl** [comment]
@JetUni This is how it looks in the [ownCloud-qt5.10.1-2.5.0.10437-daily20180824.pkg](https://download.owncloud.com/desktop/daily/ownCloud-qt5.10.1-2.5.0.10437-daily20180824.pkg) (macOS):

| Local Folder | New Option in Wizard | Add Folder Sync | Select Local folder | Select Remote Folder |
|---|---|---|---|---|
| ![01_local folder on desktop](https://user-images.githubusercontent.com/214010/44617559-f119dc80-a864-11e8-805f-626c661145e8.png) | ![02_create fsc 2](https://user-images.githubusercontent.com/214010/44617560-f1b27300-a864-11e8-8332-f6ef01a8940e.png) | ![03_create fsc 2](https://user-images.githubusercontent.com/214010/44617561-f1b27300-a864-11e8-81a4-37a1cf8eaa50.png) | ![04_select local folder](https://user-images.githubusercontent.com/214010/44617562-f1b27300-a864-11e8-8539-d0e3731bbace.png) | ![05_select remote folder](https://user-images.githubusercontent.com/214010/44617563-f1b27300-a864-11e8-9146-c8cd156cca3a.png) |

Here you can find daily builds for Win and Linux:
https://download.owncloud.com/desktop/daily/?C=M;O=D

We'd love to hear your feedback what can be improved, or if there's something missing.

**Comment by michaelstingl** [comment]
@JetUni Okay, understand. Thanks! Currently there is no good concept to have files inside a sync folder, that doesn't get uploaded. There are states where this could be the case (e.g. add local files to a read-only folder), but then it's handled as conflict or error. Need to think about it…

**Comment by JetUni** [comment]
Any update on this? Could it be left open at least?

**Comment by guruz** [comment]
We can keep this open for discussion even though there is nothing planned in this direction currently.
