### ISSUE TITLE
[Linux] [Cinnamon Mint] tray icon moves away from tray when using two monitors

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#4315]
The tray icon is suddenly repositioned. It can be found in the top righthand area of the primary desktop.
![bildschirmfoto vom 2015-12-25 01 25 36](https://cloud.githubusercontent.com/assets/1108546/11998626/bb8c563c-aaa7-11e5-931e-b7a417b85031.png)

It is fully functional. The screenshot was taken with the mouse pointer hovering over the icon, a baloon help appears.

**Comment by guruz** [comment]
Which desktop environment is that?
Which Qt version? (Would it be fixed by a newer Qt version?)

**Comment by fmoc** [comment]
I don't think this still happens. In case it does, please don't hesitate to reopen this issue.
