### ISSUE TITLE
Clients can't login on ownCloud 9.0 with LDAP auth

### ISSUE THREAD

**Issue by chrivieh** [owncloud/client#4607]
### Expected behaviour
The client should be able to login to ownCloud 9.0 which uses LDAP authentication.

### Actual behaviour
The client asks for the password and, if entered, it prints `No connection to ownCloud at https://url.to.owncloud/. The provided credentials are not correct` If I try to add a new account to the client, it replies `Access forbidden by server. To verify that you have proper access, click here (link to https://url.to.owncloud/) to access the service with your browser.`
However, on the ownCloud web interface it is possible to log in with the same credentials.
Using the owncloudcmd `owncloudcmd -u myuser /tmp/owncloud https://url.to.owncloud/` I get the following output: https://gist.github.com/chrivieh/508427109e59950b62c5

### Steps to reproduce
1. Open ownCloud client
2. Press on Account > Log in
3. Enter password.

### Server configuration
Operating system: Ubuntu 14.04 LTS

Web server: Apache 2.4.7

Database: percona-xtradb-cluster-galera-3 with maxscale loadbalancer

PHP version: 5.5.9

ownCloud version: 9.0.0

Storage backend: Netapp

### Client configuration
Client version: 2.1.1

Operating system: Arch Linux; but it does
OS language: english

Installation path of client: /usr/bin/owncloud ; /usr/bin/owncloudcmd

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
owncloud client: https://gist.github.com/chrivieh/68c020ced4fcf8d9901c
owncloudcmd: https://gist.github.com/chrivieh/508427109e59950b62c5

2. Web server error log:
web server does not log an error.

3. ownCloud log (data/owncloud.log):
ownCloud does not log an error.

**Comment by LukasReschke** [comment]
Please try again with the 9.0.1 beta. We've fixed some issues with regard to LDAP there: https://owncloud.org/install/#testing-development

**Comment by chrivieh** [comment]
Ok, I tried this, but unfortunately it still does not work.. The same error occurs.

**Comment by blizzz** [comment]
@chrivieh can you try whether directly going against the webdav endpoint works for you?

```
curl -u LOGIN -i -X PROPFIND http://owncloud.server/remote.php/webdav/
```

**Comment by chrivieh** [comment]
@blizzz it seems to work. That's the response:
```
HTTP/1.1 302 Found
Cache-Control: no-cache
Content-length: 0
Location: https://owncloud.server
Connection: close
```

**Comment by chrivieh** [comment]
@blizzz I'm sorry, checked against the wrong url (forgot the https). So, that's the output I get:
```
HTTP/1.1 401 Unauthorized
Date: Thu, 24 Mar 2016 11:57:03 GMT
Server: Apache/2.4.7 (Ubuntu)
Set-Cookie: ***=***; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=.....; path=/; httponly
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
WWW-Authenticate: Basic realm="sabre/dav"
Transfer-Encoding: chunked
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured</s:message>
</d:error>
```

**Comment by chrivieh** [comment]
Guys, I already found the error. Because of the message `Either the client didn't send one, or the server is mis-configured` I checked again the configuration of the owncloud server and it seems that the `AllowOverride` setting changed from `All` to `None`. That was the reason why the clients couldn't connect anymore. I'm sorry for bothering you!

**Comment by blizzz** [comment]
@chrivieh thanks for re-checking and I am glad you figured it out :)

**Comment by Ark74** [comment]
@chrivieh  What file did you edit?

**Comment by chrivieh** [comment]
@Ark74 you need to set it in the apache config of the owncloud site in `/etc/apache2/sites-enabled`. see https://doc.owncloud.org/server/9.0/admin_manual/installation/source_installation.html#apache-web-server-configuration

**Comment by Ark74** [comment]
@chrivieh thanks, i figured out my problem, when preparing the custom package to upgrade owncloud i skipped .htaccess and .users.ini that caused my issue, now it's solved and working fine. Thanks
