### ISSUE TITLE
[Windows] [2.2.1] memory going up and crash with no report after continuous running when having multiple accounts/folders

### ISSUE THREAD

**Issue by MU7L3Y** [owncloud/client#4976]
### Expected behaviour

Sync should continue to work and the client should always continue to run and report crash.
### Actual behaviour

After maybe 2-3 days of the client running (can't remember exactly) the client just disappears from the tray with no warning or error or crash report.
### Steps to reproduce
1. Run the client 2.2.1 for a few days. I have 18 folders set up to sync with folder 18 paused. Folder 17 has about 1.6GB that is synced already and only a few files change daily.
2. Client disappears from tray and is not running.
### Server configuration

Operating system: Linux Shared Hosting
Web server: Apache
Database: MySQL
PHP version: 5.5.36
ownCloud version: 9.0.2
Storage backend: local data folder
### Client configuration

Client version: 2.2.1
Operating system: Windows Server 2012 R2
OS language: English
Installation path of client: C:\Program Files (x86)\ownCloud\owncloud.exe
### Logs
1. Nothing output so now running the client again with --logfile log.txt
2. Web server error log: Nothing
3. ownCloud log (data/owncloud.log): Nothing
4. Windows event viewer log:

```
Faulting application name: owncloud.exe, version: 2.2.1.6146, time stamp: 0x00000000
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x35d135ab
Exception code: 0x40000015
Fault offset: 0x00021d98
Faulting process id: 0x1494
Faulting application start time: 0x01d1c63d71fa6c3a
Faulting application path: C:\Program Files (x86)\ownCloud\owncloud.exe
Faulting module path: C:\Program Files (x86)\ownCloud\libstdc++-6.dll
Report Id: 9a23b37f-340c-11e6-80d0-001e67ca7079
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by MU7L3Y** [comment]
Further to this I have noticed watching the client all day that the memory usage is slowly creeping up even when no syncing is taking place.

**Comment by guruz** [comment]
Would you please try a nightly build? We have fixed things there which might help:
http://download.owncloud.com/desktop/daily/ownCloud-2.2.1.6173-nightly20160617-setup.exe

Please report back then...

**Comment by guruz** [comment]
Can you also watch the memory usage?

**Comment by MU7L3Y** [comment]
Ok I have installed that nightly now. Will report back when I give it a few days test.

**Comment by MU7L3Y** [comment]
So far after 18 hours running it has continuously crept up from 78MB Memory to now 568MB. It only uploaded 7 small files in that time. I'll let it keep going and see what it does..

**Comment by MU7L3Y** [comment]
Over 40 hours now and memory is still climbing even though no syncing has occurred. 1182MB now...

**Comment by guruz** [comment]
Hm. Could you please double check the client settings dialog if you are really using this build?CC @ogoffart                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: JohnSent: Sonntag, 19. Juni 2016 03:03To: owncloud/clientReply To: owncloud/clientCc: Markus Goetz; CommentSubject: Re: [owncloud/client] [Windows] [2.2.1] crash with no report after continuous running (#4976)Over 40 hours now and memory is still climbing even though no syncing has occurred. 1182MB now...

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by dragotin** [comment]
@MU7L3Y do you have the Activity-App enabled, so that you see activities on the sync client?
And are you using overlay icons in the file manager?

**Comment by MU7L3Y** [comment]
Just checked now and the client has closed without crash report.
Client says Version 2.2.1-nightly20160617 (build 6173) and yes I am using overlay icons.
I don't have the activity app enabled on the cloud server but the sync client shows activity. As I said before only 7 small files were uploaded in all that time.

Last log file that was made:
[owncloud.log.506.zip](https://github.com/owncloud/client/files/322526/owncloud.log.506.zip)

**Comment by guruz** [comment]
@MU7L3Y So the memory continued to climb?

We'd have a 2.2.3 nightly build which contains some crash fixes and memory improvements that @jturcotte and @ogoffart did. Maybe test this one instead?
http://download.owncloud.com/desktop/daily/ownCloud-2.2.3.6196-nightly20160621-setup.exe

FYI @ckamm

**Comment by MU7L3Y** [comment]
@guruz Yes the memory continues to climb. Installing that nightly build now. Will report back how it goes.

**Comment by guruz** [comment]
@MU7L3Y Sorry, I got one more nightly build coming up.. 10 minutes.

**Comment by guruz** [comment]
@MU7L3Y New nightly is called http://download.owncloud.com/desktop/daily/ownCloud-2.2.3.6198-nightly20160621-setup.exe

**Comment by MU7L3Y** [comment]
Ok installed that one now...

**Comment by MU7L3Y** [comment]
36 hours running that build and memory has steadily risen from 56MB to 1092MB and counting.

**Comment by MU7L3Y** [comment]
OK it lasted a little longer but checked now and the client has closed 2 hours ago. It made 673 log files this time. It kinda seems like it is holding each folder/account that is syncing in memory and not letting go each time it does it checks. As said in OP I have 18 folders/accounts syncing with folder 18 paused. Not sure if that matters because on another PC (win 7) getting that entire 18 folder sync from the owncloud server, the client also builds up the memory. I don't notice it crash because that PC gets shut down each day.

Last log file made:
[owncloud.log.673.zip](https://github.com/owncloud/client/files/330966/owncloud.log.673.zip)

Windows event log:
```
Faulting application name: owncloud.exe, version: 2.2.3.6198, time stamp: 0x00000000
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x35d135ab
Exception code: 0x40000015
Fault offset: 0x00021d32
Faulting process id: 0x19f8
Faulting application start time: 0x01d1cbae6b8b132e
Faulting application path: C:\Program Files (x86)\ownCloud\owncloud.exe
Faulting module path: C:\Program Files (x86)\ownCloud\libstdc++-6.dll
Report Id: b7f5304c-3986-11e6-80d0-001e67ca7079
Faulting package full name: 
Faulting package-relative application ID: 
```

I've downloaded and am running this build now:
http://download.owncloud.com/desktop/daily/ownCloud-2.2.3.6201-nightly20160623-setup.exe

**Comment by MU7L3Y** [comment]
Been running the client on my win 7 PC all day with the build I posted above and it's memory hasn't gone up, just hovering around 82MB. The win server however is still a problem.

**Comment by guruz** [comment]
@MU7L3Y I'm not sure I understand. What are the two machines you have? On which one it does not work? Same build? Same sync directories etc?

**Comment by MU7L3Y** [comment]
@guruz on the windows server 2012 x64 I am syncing 18 individual folders/accounts to folders in the owncloud server. I then have a windows 7 x64 pc that is syncing from the owncloud server all those folders as one "account" in the owncloud client. The windows server is the one that is not working. This is using build 2.2.3.6201

**Comment by guruz** [comment]
Thanks.
@jturcotte @ckamm @ogoffart So maybe this memory leak only reproduces if you have multiple accounts and sync folders setup?

**Comment by mcastroSG** [comment]
@guruz @MU7L3Y I have recreated a scenario:

Client OS: Windows Server 2008
Client Version: Version 2.2.3-nightly20160628 (build 6210)

7 Shared Sync Folders , 3 of them sync forever due to a script that "touch" some files inside these folders. After 100 hundred executions of this test we could found that memory has been incremented by 3 MB. Still have not found nothing that brings light to this issue but still doing some tests.

**Comment by MU7L3Y** [comment]
Maybe try having one account sync paused? Just guessing here...

**Comment by MU7L3Y** [comment]
@mcastroSG @guruz I have just installed version 2.2.3-nightly20160629 (build 6212). Will report back how that one goes.

**Comment by MU7L3Y** [comment]
I've run build 6212 for a day now and it's only gone from 85MB to 98MB. Seems overnight it didn't keep creeping up which is good but everytime I open and close the UI it goes up a little (like 1MB or less) but doesn't ever drop back..

**Comment by MU7L3Y** [comment]
After 5 days of running it is only at 105MB. Still climbing but much much slower.

**Comment by MU7L3Y** [comment]
I've been running build 6212 for 13 days now and it is at 133MB. Still climbing ever so slowly.

**Comment by guruz** [comment]
Thanks, I think this is "good enough" for now.
Let's move this to 2.3 for re-evaluation then.

**Comment by ckamm** [comment]
@MU7L3Y Btw, your long term testing and reporting is highly appreciated! :)

**Comment by MU7L3Y** [comment]
No worries.
I've just installed build 6294 so will see how that one goes.

**Comment by MU7L3Y** [comment]
Since 2.2.3 just came out I'm installing that one now and will leave it to run.

After installing and it's first sync it is now sitting at 81.6MB

**Comment by guruz** [comment]
We haven't heard back, so i'm assuming this is fixed:)

**Comment by MU7L3Y** [comment]
@guruz Sorry I don't think it's fixed, it's just a really slow climber. It's sitting at 119MB right now.

**Comment by guruz** [comment]
@MU7L3Y For how long running?

**Comment by jturcotte** [comment]
Just my opinion, but I think that 119MB is an expected memory footprint, not a bug and definitely not of the same severity as what this issue has been tracking (i.e. ultimately crashing).

We could do some crazy work using memory pools and such tricks to try keeping it lower than this, but this isn't a bug, this would be an improvement that would need to be tracked as such.

**Comment by MU7L3Y** [comment]
@guruz 3 weeks.
@jturcotte maybe so nowadays but it was crashing earlier. :-)

**Comment by guruz** [comment]
I'd think that's OK usage. :)

But please try to have a look every few days..

**Comment by MU7L3Y** [comment]
Sure. This past week it has grown to 107MB.

**Comment by MU7L3Y** [comment]
In the past 6 days it has grown from 107MB to 183MB.

**Comment by guruz** [comment]
mhm..

**Comment by MU7L3Y** [comment]
Another 6 days and it's now at 219MB.

**Comment by guruz** [comment]
Let's see if we can do something for 2.3 or not.

**Comment by MU7L3Y** [comment]
ok well let me know if I need to do anything to help. Thanks

**Comment by MU7L3Y** [comment]
7 days later and now 227MB.
I'm installing 2.2.4 now.

**Comment by MU7L3Y** [comment]
I've had to restart the server a couple of times these past weeks.
Since restarting it 5 and a half days ago it is now sitting at 130MB.

**Comment by MU7L3Y** [comment]
13 days running and up to 183MB. This is Version 2.2.4 (build 6408).

**Comment by MU7L3Y** [comment]
48 days and 16 hours and it's at 129MB so it seems not that critical anymore.
This is using Version 2.2.4 build 6408.

**Comment by ogoffart** [comment]
Closing the issue then.

Thanks for the testing.
