### ISSUE TITLE
Shibboleth accounts don't work after restart

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5408]
Create a shibboleth account, restart the client. Afterwards `master` is unable to connect to the account.

The testing propfind gets replies like this:
```
12-21 14:40:12:600 21736 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 200 ""
12-21 14:40:12:600 21736 OCC::ConnectionValidator::slotAuthFailed: ZZZ 200 "\n<html>\n  <head>\n        <title>TestShib Identity Provider Login</title>\n
```
and initial investigation shows that DummyCredentials are used for the shib account after a restart.

**Comment by ckamm** [comment]
Should be fixed by https://github.com/owncloud/client/pull/5409

**Comment by SamuAlfageme** [comment]
Not getting the PROPFIND error anymore, but it's still reproducing complaining about the shib credentials being wrong ones:

```
OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Undefined" -> "Credentials Wrong"
OCC::AccountState::setState: AccountState state change:  "Disconnected" -> "Configuration error"
```
The account is left in a "*Configuration error*" state, that allows to log out; but trying to log in again does not give the user the chance to enter the credentials for shibboleth again.

**Comment by ckamm** [comment]
@SamuAlfageme Did you re-setup the account? I can't fix old accounts, because they're saved as "dummy" accounts and not "shiboleth" accounts... :/

Possibly we could add fixup code to detect broken accounts and repair them? I'll look at that.

**Comment by ckamm** [comment]
@SamuAlfageme Try again now, broken accounts should be magically repaired by looking at credential-specific setting keys and detecting the account-type from there.

**Comment by SamuAlfageme** [comment]
All shibb accounts working as expected now 🎉

There's this one detail, though, that bugs me: 

### Steps to reproduce:
1. Login with a valid shibb account and sync your files
2. Remove keychain entry for the account 
3. Restart the client, it asks for shibb credentials
4. Input **a different but valid account**
5. An error is displayed (see the one for the http://testshib.org down)
6. Click `Log in` in the account view
7. Account is logged back without entering the credentials again

![screenshot 2017-01-13 10 25 47](https://cloud.githubusercontent.com/assets/2644445/21925135/5adac4b8-d97c-11e6-82d9-c3882adf69e2.png)

I assume wiping the keychain entry is not enough to force log out and the client is using some session token to login back again, but then, **why it asks for the credentials, if they're not needed?**,

**Comment by ckamm** [comment]
@SamuAlfageme Nice find, that's an important bug, but it's unrelated to this one and needs its own ticket. Can I ask you to make one?
