### ISSUE TITLE
[Smashbox] basicSync fails because test case is too fast

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5913]
https://jenkins.owncloud.com/view/smashbox/job/smashbox-daily-stable10-basicSync/lastFailedBuild/artifact/smashbox.log/*view*/
https://jenkins.owncloud.com/view/smashbox/job/smashbox-daily-stable8.2-basicSync/lastFailedBuild/artifact/smashbox.log/*view*/
https://jenkins.owncloud.com/view/smashbox/job/smashbox-daily-stable9-basicSync/lastFailedBuild/artifact/smashbox.log/*view*/

```
********************************************************************************
(8) checker:  FINAL CHECK
********************************************************************************
2017-07-19 00:03:51,086 - INFO - checker - running 'ls -lh --full-time /smashdir/test_basicSync/checker'
2017-07-19 00:03:51,087 - INFO - loser - stdout: total 11M
drwxr-xr-x 2 root root 4.0K 2017-07-19 00:03:47.366381809 +0000 Documents
drwxr-xr-x 2 root root 4.0K 2017-07-19 00:03:47.410383537 +0000 Photos
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.962405204 +0000 TEST_FILE_ADDED_BOTH.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.962405204 +0000 TEST_FILE_ADDED_LOSER.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.000000000 +0000 TEST_FILE_ADDED_WINNER.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.958405046 +0000 TEST_FILE_MODIFIED_BOTH.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.958405046 +0000 TEST_FILE_MODIFIED_LOSER.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:46.000000000 +0000 TEST_FILE_MODIFIED_NONE.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.000000000 +0000 TEST_FILE_MODIFIED_WINNER.dat
-rw-r--r-- 1 root root 3.5M 2017-07-19 00:03:46.000000000 +0000 ownCloud_User_Manual.pdf

2017-07-19 00:03:51,090 - INFO - checker - stdout: total 11M
drwxr-xr-x 2 root root 4.0K 2017-07-19 00:03:50.450502860 +0000 Documents
drwxr-xr-x 2 root root 4.0K 2017-07-19 00:03:50.482504116 +0000 Photos
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.000000000 +0000 TEST_FILE_ADDED_BOTH.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.000000000 +0000 TEST_FILE_ADDED_LOSER.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.000000000 +0000 TEST_FILE_ADDED_WINNER.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.000000000 +0000 TEST_FILE_MODIFIED_BOTH.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.000000000 +0000 TEST_FILE_MODIFIED_LOSER.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:46.000000000 +0000 TEST_FILE_MODIFIED_NONE.dat
-rw-r--r-- 1 root root 977K 2017-07-19 00:03:47.000000000 +0000 TEST_FILE_MODIFIED_WINNER.dat
-rw-r--r-- 1 root root 3.5M 2017-07-19 00:03:46.000000000 +0000 ownCloud_User_Manual.pdf

2017-07-19 00:03:51,132 - ERROR - loser - inconsistent md5 of /smashdir/test_basicSync/loser/TEST_FILE_ADDED_BOTH.dat: expected f8f157ccec2b134dc35b566ef1d5e197, got 647cbb844d2e3f8d33da67e9f13f27a3 error_check(actual_md5 == md5, "inconsistent md5 of %s: expected %s, got %s"%(fn,md5,actual_md5)) failed in expect_content() ["/smashbox/lib/test_basicSync.py" at line 71]
2017-07-19 00:03:51,137 - ERROR - loser - inconsistent md5 of /smashdir/test_basicSync/loser/TEST_FILE_MODIFIED_BOTH.dat: expected f8f157ccec2b134dc35b566ef1d5e197, got 647cbb844d2e3f8d33da67e9f13f27a3 error_check(actual_md5 == md5, "inconsistent md5 of %s: expected %s, got %s"%(fn,md5,actual_md5)) failed in expect_content() ["/smashbox/lib/test_basicSync.py" at line 71]
2017-07-19 00:03:51,138 - ERROR - loser - expected 2 got 0 conflict files error_check(len(expected_conflict_files) == len(actual_conflict_files), "expected %d got %d conflict files"%(len(expected_conflict_files),len(actual_conflict_files))) failed in expect_conflict_files() ["/smashbox/lib/test_basicSync.py" at line 91]
2017-07-19 00:03:51,139 - ERROR - loser - expected conflict file for TEST_FILE_ADDED_BOTH not found error_check(any([bfn in fn for fn in actual_conflict_files]), "expected conflict file for %s not found"%bfn) failed in expect_conflict_files() ["/smashbox/lib/test_basicSync.py" at line 99]
2017-07-19 00:03:51,140 - ERROR - loser - expected conflict file for TEST_FILE_MODIFIED_BOTH not found error_check(any([bfn in fn for fn in actual_conflict_files]), "expected conflict file for %s not found"%bfn) failed in expect_conflict_files() ["/smashbox/lib/test_basicSync.py" at line 99]
2017-07-19 00:03:52,108 - ERROR - loser - 5 error(s) reported
```

**Comment by ckamm** [comment]
I can not reproduce this on linux with the 2.3 or master branch.

**Comment by guruz** [comment]
@ckamm should be 2.3.2 according to the log here
https://jenkins.owncloud.com/view/smashbox/job/smashbox-daily-stable10-basicSync/lastFailedBuild/console

**Comment by guruz** [comment]
yes, the docker image should pull in v2.3.2.tar.gz hmm
Would be nice if the client was run in verbose..

**Comment by guruz** [comment]
@tboerger @DeepDiver1975 @mrow4a Can we somehow access the files in /smashdir of this job? https://jenkins.owncloud.com/view/smashbox/job/smashbox-daily-stable10-basicSync/lastFailedBuild/console

(in not-logged in, we only can download smashbox.log)

**Comment by ogoffart** [comment]
/me also tried basicSync on my machine worked fine.

**Comment by mrow4a** [comment]
Yep, I also had the same problem, that localy everything is fine, but not there.

**Comment by guruz** [comment]
@tboerger @DeepDiver1975 @michaelstingl We'd need those logs to debug then

**Comment by michaelstingl** [comment]
> Would be nice if the client was run in verbose..

@guruz What is needed to run the client in verbose? Where?

**Comment by tboerger** [comment]
You can see at https://jenkins.owncloud.com/view/smashbox/job/smashbox-daily-master-chunking/26/ that smashdir.tar.xz gets stored now, are the artifacts now enough for further debugging?

**Comment by guruz** [comment]
@tboerger We'd need the smashdir.tar.xz for basicSync now, not chunking. I think chunking failure is expected in 2.3.2 ( @mrow4a please confirm) but should be fixed with client 2.3.3..
Can you re-trigger?

**Comment by tboerger** [comment]
Ok, now the scripting is fixed, you can always get the smashdir.tar.xz artifact from the build for further debugging.

**Comment by tboerger** [comment]
> @tboerger We'd need the smashdir.tar.xz for basicSync now, not chunking. I think chunking failure is expected in 2.3.2 ( @mrow4a please confirm) but should be fixed with client 2.3.3..
> Can you re-trigger?

Retriggered https://jenkins.owncloud.com/view/smashbox/job/smashbox-daily-master-basicSync/33/

**Comment by michaelstingl** [comment]
![cursor_and_smashbox-daily-master-basicsync__33__jenkins_](https://user-images.githubusercontent.com/214010/28461882-f985f6ce-6e18-11e7-876e-112da9dd6698.png)

Looks good (but still failing). @tboerger Thanks!

**Comment by ogoffart** [comment]
Investingating the logs:  

Winner step 03 is supposed to upload TEST_FILE_MODIFIED_BOTH and TEST_FILE_ADDED_BOTH
This seems to succeed:

```
"INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16);" 5426047158163907264 24 "TEST_FILE_ADDED_BOTH.dat" 1072 "1500632674" "0" "b5d870706e718acdff579987af510610" "00000506ocq7tspwmomy" "" 1000000 0 "9e2d9f3e2a1ab61b4b948c18bc4340ce2aaaa9a1" "SHA1" 1
"DELETE FROM uploadinfo WHERE path=?1" "TEST_FILE_ADDED_BOTH.dat"
void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "upload file start" and starting new transaction
void OCC::SyncEngine::slotItemCompleted(const SyncFileItemPtr&) "TEST_FILE_ADDED_BOTH.dat" INSTRUCTION_NEW 4 ""
[...]
"INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16);" -2716234513854664527 27 "TEST_FILE_MODIFIED_BOTH.dat" 1096 "1500632674" "0" "a4ce93b15e239a1049319a2aa40d5a60" "00000497ocq7tspwmomy" "RDNVW" 1000000 0 "9e2d9f3e2a1ab61b4b948c18bc4340ce2aaaa9a1" "SHA1" 1
"DELETE FROM uploadinfo WHERE path=?1" "TEST_FILE_MODIFIED_BOTH.dat"
void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "upload file start" and starting new transaction
void OCC::SyncEngine::slotItemCompleted(const SyncFileItemPtr&) "TEST_FILE_MODIFIED_BOTH.dat" INSTRUCTION_SYNC 4 ""
```

But in loser step 04,  we the files don't get downloaded.  The discovery correctly annotates them to NEW (but why not EVAL for TEST_FILE_MODIFIED_BOTH ?), but then the reconcile does mark them only as update_metadata:

```
[9] _csync_merge_algorithm_visitor  INSTRUCTION_NONE               client file: TEST_FILE_ADDED_BOTH.dat
[9] _csync_merge_algorithm_visitor  INSTRUCTION_NONE               client file: TEST_FILE_MODIFIED_BOTH.dat
[8] _csync_merge_algorithm_visitor  INSTRUCTION_UPDATE_METADATA    server file: TEST_FILE_ADDED_BOTH.dat
[8] _csync_merge_algorithm_visitor  INSTRUCTION_UPDATE_METADATA    server file: TEST_FILE_MODIFIED_BOTH.dat
```

Could they have the same mtime?
That could very well be: both sync were done at 10:24:34 in less than one second.
And we indeed resolve conflicts for file that have the same mtime and the same size (and they have the same size)

I guess on our local machine the sync is slower maybe. I'm using a sqlite database locally, that could explain.

maybe we should add sleep(1) between every step?

**Comment by tboerger** [comment]
Yeah, too fast tests :P generally that's a good sign

**Comment by mrow4a** [comment]
Makes sense @ogoffart

**Comment by mrow4a** [comment]
@ogoffart perfect shot - https://jenkins.owncloud.com/view/smashbox/ - closing

**Comment by mrow4a** [comment]
https://github.com/owncloud/smashbox/pull/165
