### ISSUE TITLE
[2.5.0] [Linux] Crash when internet connection is lost during runtime

### ISSUE THREAD

**Issue by doronbehar** [owncloud/client#6790]
### Expected behaviour
No crash happens.

### Actual behaviour
The sync client exits with core dumped when internet connection is lost during it's runtime.

### Steps to reproduce

1. Launch the client.
2. Close your WiFi connection or disconnect your Ethernet cable.

### Server configuration

- Operating system: Arch Linux
- Web server: Apache
- Database: PostgreSQL
- PHP version: 7.2.10
- ownCloud version: Nextcloud 14.0.1
- Storage backend (external storage): None?

### Client configuration
- Client version: 2.5.0
- Operating system: Arch Linux
- OS language: `en_US-UTF-8`
- Qt version used by client package (Linux only, see also Settings dialog): `5.11.2`, built against `5.11.1`
- Client package (From ownCloud or distro) (Linux only): Distribution repositories

Installation path of client: Prefix? `/usr/` I guess..

### Logs

1. Client logfile: [Output of `owncloud --logwindow` or `owncloud --logfile log.txt`](https://gist.github.com/d67bf113c3f078403747f4c156849080)
2. Web server error log: Nothing interesting, only mentions of connections made were found there.
3. Server logfile: ownCloud log (`data/owncloud.log`): Nothing mentioning my client found there (`data/nextcloud.log`)

**Comment by doronbehar** [comment]
BTW, I have a suspicion that this issue is related to a certain library, since I get a very similar behaviour with another QT based application - https://github.com/Martchus/syncthingtray . I haven't reported it there but I suspect this can be worked out here as a start.

**Comment by ogoffart** [comment]
Hi, Could you get a backtrace of the crash?
I could not reproduce the crash localy.

**Comment by ogoffart** [comment]
Might or might not be releated to this crash:  https://sentry.io/owncloud/desktop-win-and-mac/issues/698694072/

```
Crash: EXCEPTION_ACCESS_VIOLATION_READ at 0xbb9c000
  Module "owncloudsync.dll", in QVector<OCC::PropagatorJob
  File "owncloudpropagator.cpp", line 842, in OCC::PropagatorCompositeJob::slotSubJobFinished(OCC::SyncFileItem::Status)
  Module "owncloudsync.dll", in QtPrivate::QSlotObject<void
  Module "owncloudsync.dll", in OCC::PropagateUploadFileCommon::abortWithError(OCC::SyncFileItem::Status,QString
  Module "owncloudsync.dll", in OCC::PropagateUploadFileCommon::commonErrorHandling(OCC::AbstractNetworkJob
  File "propagateuploadv1.cpp", line 208, in OCC::PropagateUploadFileV1::slotPutFinished()
  File "abstractnetworkjob.cpp", line 234, in OCC::AbstractNetworkJob::slotFinished()
```

I've tried several ways to reproduce it, or to understand what could go wrong without success.

**Comment by doronbehar** [comment]
Are you talking about the core dump? [Here it is](https://gist.github.com/doronbehar/3bca7671a5f23b1bf029f33a14e22065) - from `coredumpctl info`.

**Comment by guruz** [comment]
> Are you talking about the core dump? Here it is 

Hm, this would be more useful with debug symbols from QtNetwork. :-( 
@ogoffart Does it make sense that @doronbehar 's stack trace mostly shows QtNetwork and not the event loop etc?
You can also run the client completely in a debugger:
```
gdb owncloud 
run
thread apply all bt
```

> I have a suspicion that this issue is related to a certain library, since I get a very similar behaviour with another QT based application 

I checked https://bugreports.qt.io/ but didnt see anything.

@doronbehar Can you click the 'lock' icon in the account tab of the client and check if it mentions HTTP2? 

> Client version: 2.5.0

Did it work with previous versions?

**Comment by ogoffart** [comment]
Maybe the same as what was fixed there:  https://github.com/owncloud/client/pull/6798

```
ownCloud version: Nextcloud 14.0.1
```

I don't think nextcloud supports chunking ng, so the PropagateUploadFileV1 are used, and that's where the bug was.

**Comment by doronbehar** [comment]
I've had the same problem with previous versions as well and [as I said](https://github.com/owncloud/client/issues/6790#issuecomment-426689478), the same problem persists with another program that depends on `qt5-webkit`.
@guruz the 'lock' icon doesn't mention `http2` and it has the following text:
```
TLSv1.2, RSA, ECDH, CHACHA20, POLY1305(256)
No support for SSL session tickets/identifiers
```

**Comment by guruz** [comment]
@doronbehar We really need the backtrace, see the lines with gdb in https://github.com/owncloud/client/issues/6790#issuecomment-429948608
Thanks

**Comment by doronbehar** [comment]
Thanks for maintaining an interest in this bug, Should I recompile QtNetwork with debug symbols? Should I compile the client with debug symbols as well? As explained [here](https://doc.owncloud.org/desktop/2.3/building.html#generic-build-instructions)? As for compiling QtNetwork with debug symbols that would mean I should clone the repository or download the sources according and run `./configure` with `-developer-build`? I've read this [here](https://doc.qt.io/qt-5/configure-options.html).

**Comment by dschmidt** [comment]
You can possibly install debug packages from your distro

**Comment by ogoffart** [comment]
I'm quite confident this crash is fixed by #6798,  maybe you can try to build yourself the 2.5 branch ans see if you can reproduce the crash.

**Comment by doronbehar** [comment]
Thanks for the links, I've installed `qt5-webkit-debug` from the unofficial `qt-debug` repository and tested the issue again with a debug build against `master` the issue was still there.

I ran it through `gdb` and it took it much longer to start (I guess that's normal..) and here is the output of it:

```
(gdb) thread apply all bt
(gdb) run
Starting program: /var/code/doron/client/build/bin/owncloud
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffed065700 (LWP 30742)]
[New Thread 0x7fffeac68700 (LWP 30743)]
[New Thread 0x7fffea049700 (LWP 30744)]
[New Thread 0x7fffe980c700 (LWP 30745)]
propsReply "Method \"GetAll\" with signature \"s\" on interface \"org.freedesktop.DBus.Properties\" doesn't exist\n"
nmReply "Method \"GetDevices\" with signature \"\" on interface \"org.freedesktop.NetworkManager\" doesn't exist\n"
"Object path cannot be empty"
[Detaching after fork from child process 30746]
[Detaching after fork from child process 30747]
[New Thread 0x7fffdb5d4700 (LWP 30752)]
[New Thread 0x7fffdab81700 (LWP 30753)]
[New Thread 0x7fffda380700 (LWP 30754)]
[New Thread 0x7fffd9b7f700 (LWP 30755)]
[New Thread 0x7fffd937e700 (LWP 30756)]
[New Thread 0x7fffd8b7d700 (LWP 30757)]
[New Thread 0x7fffc3fff700 (LWP 30758)]
[New Thread 0x7fffc37fe700 (LWP 30759)]
[Detaching after fork from child process 30761]
[New Thread 0x7fffc2ffd700 (LWP 30766)]
[Thread 0x7fffc37fe700 (LWP 30759) exited]
[Thread 0x7fffda380700 (LWP 30754) exited]

Thread 1 "owncloud" received signal SIGSEGV, Segmentation fault.
0x00007ffff3929184 in ?? () from /usr/lib/libQt5Core.so.5
(gdb) quit
A debugging session is active.

        Inferior 1 [process 30679] will be killed.

Quit anyway? (y or n) n
Not confirmed.
```

I hope it's OK I used `thread apply all bt` before the `run` command, I don't really know how to use `gdb`.. it seems there is still a thread running (the tray icon hasn't disappeared as well) while all the other threads were killed. How shall I give you the stack-traces?

**Comment by guruz** [comment]
@doronbehar No, you need to run the ```thread apply all bt``` after the crash since it is about the stack trace after/during the crash. So the `run` needs to come before. You can just type it now if you didn't quit gdb yet.

**Comment by doronbehar** [comment]
I've installed `qt5-base-debug` as well and I got more function names for the backt-race so here they are:

```
[Thread 0x7fffc3fff700 (LWP 20546) exited]
[New Thread 0x7fffc3fff700 (LWP 20646)]

Thread 1 "owncloud" received signal SIGSEGV, Segmentation fault.
0x00007ffff3924369 in QByteArray::reserve (asize=0, this=0x7fffff7ff070) at ../../include/QtCore/../../src/corelib/tools/qbytearray.h:471
471     ../../include/QtCore/../../src/corelib/tools/qbytearray.h: No such file or directory.
(gdb) thread apply all bt

Thread 21 (Thread 0x7fffc3fff700 (LWP 20646)):
#0  0x00007ffff31a0ef6 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff376e5fd in QWaitConditionPrivate::wait_relative(unsigned long) (time=30000, this=0x7fffbc005ad0) at thread/qwaitcondition_unix.cpp:133
#2  0x00007ffff376e5fd in QWaitConditionPrivate::wait(unsigned long) (time=30000, this=0x7fffbc005ad0) at thread/qwaitcondition_unix.cpp:141
#3  0x00007ffff376e5fd in QWaitCondition::wait(QMutex*, unsigned long) (this=this@entry=0x7fffbc005920, mutex=mutex@entry=0x7fffbc0056a0, time=30000) at thread/qwaitcondition_unix.cpp:215
#4  0x00007ffff3766024 in QThreadPoolThread::run() (this=0x7fffbc005910) at ../../include/QtCore/../../src/corelib/thread/qmutex.h:240
#5  0x00007ffff376df65 in QThreadPrivate::start(void*) (arg=0x7fffbc005910) at thread/qthread_unix.cpp:367
#6  0x00007ffff319aa9d in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff32b1b23 in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7fffc37fe700 (LWP 19995)):
#0  0x00007ffff32a6c21 in poll () at /usr/lib/libc.so.6
#1  0x00007ffff300fee0 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff300ffce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff396efc9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffb0000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#4  0x00007ffff391a8cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffc37fdd20, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#5  0x00007ffff3763eb9 in QThread::exec() (this=<optimized out>) at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#6  0x00007ffff376df65 in QThreadPrivate::start(void*) (arg=0x555555ab0e70) at thread/qthread_unix.cpp:367
#7  0x00007ffff319aa9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff32b1b23 in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7fffd8b7d700 (LWP 19988)):
#0  0x00007ffff32a6c21 in poll () at /usr/lib/libc.so.6
#1  0x00007ffff300fee0 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff300ffce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff396efc9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffbc000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#4  0x00007ffff391a8cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffd8b7cd20, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#5  0x00007ffff3763eb9 in QThread::exec() (this=<optimized out>) at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#6  0x00007ffff376df65 in QThreadPrivate::start(void*) (arg=0x555555f9efe0) at thread/qthread_unix.cpp:367
#7  0x00007ffff319aa9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff32b1b23 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7fffd9b7f700 (LWP 19986)):
#0  0x00007ffff32a6c21 in poll () at /usr/lib/libc.so.6
#1  0x00007ffff300fee0 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff3010f62 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff1994c28 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff2fd93eb in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff319aa9d in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff32b1b23 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7fffdab81700 (LWP 19984)):
#0  0x00007ffff32a6c21 in poll () at /usr/lib/libc.so.6
#1  0x00007ffff300fee0 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff300ffce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff3010022 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff2fd93eb in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff319aa9d in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff32b1b23 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffdb5d4700 (LWP 19983)):
#0  0x00007ffff31a0afc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fffdb8231ac in  () at /usr/lib/dri/i965_dri.so
#2  0x00007fffdb822ee8 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007ffff319aa9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff32b1b23 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffe97c3700 (LWP 19976)):
#0  0x00007ffff32a6c21 in poll () at /usr/lib/libc.so.6
#1  0x00007ffff300fee0 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff300ffce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff396efc9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffe0000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#4  0x00007ffff391a8cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffe97c2cf0, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#5  0x00007ffff3763eb9 in QThread::exec() (this=this@entry=0x7ffff7f9b080 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#6  0x00007ffff7f1fba6 in QDBusConnectionManager::run() (this=0x7ffff7f9b080 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at qdbusconnection.cpp:178
#7  0x00007ffff376df65 in QThreadPrivate::start(void*) (arg=0x7ffff7f9b080 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at thread/qthread_unix.cpp:367
#8  0x00007ffff319aa9d in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff32b1b23 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffea000700 (LWP 19975)):
#0  0x00007ffff32a6c21 in poll () at /usr/lib/libc.so.6
#1  0x00007ffff300fee0 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff300ffce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff396efc9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffdc000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#4  0x00007ffff391a8cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffe9fffd20, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#5  0x00007ffff3763eb9 in QThread::exec() (this=<optimized out>) at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#6  0x00007ffff376df65 in QThreadPrivate::start(void*) (arg=0x5555559a1810) at thread/qthread_unix.cpp:367
#7  0x00007ffff319aa9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff32b1b23 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffeac5f700 (LWP 19974)):
#0  0x00007ffff32a6c21 in poll () at /usr/lib/libc.so.6
#1  0x00007fffeecec630 in  () at /usr/lib/libxcb.so.1
#2  0x00007fffeecee2db in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007fffec1dfc5a in QXcbEventReader::run() (this=0x55555597c8a0) at qxcbconnection.h:409
#4  0x00007ffff376df65 in QThreadPrivate::start(void*) (arg=0x55555597c8a0) at thread/qthread_unix.cpp:367
#5  0x00007ffff319aa9d in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff32b1b23 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffed058700 (LWP 19973)):
#0  0x00007ffff31a0afc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff35cecd1 in __gthread_cond_wait (__mutex=<optimized out>, __cond=0x7ffff717ef08 <bmalloc::PerProcess<bmalloc::Heap>::s_memory+3080>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:864
#2  0x00007ffff35cecd1 in std::condition_variable::wait(std::unique_lock<std::mutex>&) (this=this@entry=0x7ffff717ef08 <bmalloc::PerProcess<bmalloc::Heap>::s_memory+3080>, __lock=...) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00007ffff6697f14 in std::_V2::condition_variable_any::wait<std::unique_lock<bmalloc::Mutex> >(std::unique_lock<bmalloc::Mutex>&) (__lock=<synthetic pointer>..., this=<optimized out>) at /usr/include/c++/8.2.1/bits/std_mutex.h:238
#4  0x00007ffff6697f14 in std::_V2::condition_variable_any::wait<std::unique_lock<bmalloc::Mutex>, bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop()::{lambda()#1}>(std::unique_lock<bmalloc::Mutex>&, bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop()::{lambda()#1}) (__p=..., __lock=..., this=<optimized out>) at /usr/include/c++/8.2.1/condition_variable:272
#5  0x00007ffff6697f14 in bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() (this=0x7ffff717ef00 <bmalloc::PerProcess<bmalloc::Heap>::s_memory+3072>) at /usr/src/debug/qtwebkit-5.212.0-alpha2/Source/bmalloc/bmalloc/AsyncTask.h:126
#6  0x00007ffff6698039 in bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadEntryPoint(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*) (asyncTask=<optimized out>) at /usr/src/debug/qtwebkit-5.212.0-alpha2/Source/bmalloc/bmalloc/AsyncTask.h:104
#7  0x00007ffff35d5063 in std::execute_native_thread_routine(void*) (__p=0x55555595a1e0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#8  0x00007ffff319aa9d in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff32b1b23 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7fffed064040 (LWP 19882)):
#0  0x00007ffff3924369 in QByteArray::reserve(int) (asize=0, this=0x7fffff7ff070) at ../../include/QtCore/../../src/corelib/tools/qbytearray.h:471
#1  0x00007ffff3924369 in normalizeTypeInternal(char const*, char const*, bool, bool) (t=0x7fffff7ff0c8 ")", e=0x7fffff7ff0c8 ")", fixScope=false, adjustConst=true) at ../../include/QtCore/5.11.2/QtCore/private/../../../../../src/corelib/kernel/qmetaobject_moc_p.h:100
#2  0x00007ffff3924bd9 in qNormalizeType(char*, int&, QByteArray&) (d=<optimized out>, templdepth=<optimized out>, result=...) at kernel/qmetaobject.cpp:1266
#3  0x00007ffff392af36 in QMetaObject::normalizedSignature(char const*) (method=method@entry=0x7ffff428f156 "2opened()") at kernel/qmetaobject.cpp:1328
#4  0x00007ffff394a38f in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) (sender=0x555555ac3180, signal=signal@entry=0x7ffff428f156 "2opened()", receiver=receiver@entry=0x555555f9bcb0, method=method@entry=0x7ffff428f13b "2networkSessionConnected()")
    at kernel/qobject.cpp:2949
#5  0x00007ffff4183f75 in QNetworkAccessManagerPrivate::_q_networkSessionClosed() (this=this@entry=0x555555fa5e70) at access/qnetworkaccessmanager.cpp:1872
#6  0x00007ffff418413c in QNetworkAccessManagerPrivate::_q_networkSessionStateChanged(QNetworkSession::State) (this=this@entry=0x555555fa5e70, state=<optimized out>) at access/qnetworkaccessmanager.cpp:1922
#7  0x00007ffff4184588 in QNetworkAccessManagerPrivate::createSession(QNetworkConfiguration const&) (this=this@entry=0x555555fa5e70, config=...) at ../../include/QtCore/../../src/corelib/tools/qsharedpointer_impl.h:312
#8  0x00007ffff4184153 in QNetworkAccessManagerPrivate::_q_networkSessionStateChanged(QNetworkSession::State) (this=this@entry=0x555555fa5e70, state=<optimized out>) at access/qnetworkaccessmanager.cpp:1923
#9  0x00007ffff4184588 in QNetworkAccessManagerPrivate::createSession(QNetworkConfiguration const&) (this=this@entry=0x555555fa5e70, config=...) at ../../include/QtCore/../../src/corelib/tools/qsharedpointer_impl.h:312
#10 0x00007ffff4184153 in QNetworkAccessManagerPrivate::_q_networkSessionStateChanged(QNetworkSession::State) (this=this@entry=0x555555fa5e70, state=<optimized out>) at access/qnetworkaccessmanager.cpp:1923
** THIS ABOVE TWO LINES REPEAT LIKE THIS UNTIL LIKE FOREVER **
```

**Comment by ogoffart** [comment]
Ah, so this is indeed not the same as the other issue.
This looks like yet another issue with Qt's bearer management:
https://bugreports.qt.io/browse/QTBUG-58541

This does not affect our package since we disable bearer management

Interestingly it is only fixed in Qt 5.12

**Comment by doronbehar** [comment]
BTW, since apparently no one here has managed to reproduce the issue, I was wondering: What network manager do you use? I use [connman](https://01.org/connman) and since it is quiet new and still in development and very few people use it, I have a small suspicion that somehow this is the reason I'm the only one getting this crash.

Is it even possible that a behaviour of the network manager could cause `qt5-webkit` to crash like that?

**Comment by ckamm** [comment]
@ogoffart As I understand we can only take care of this with a Qt upgrade, which is likely for 2.5.2 earliest - preferably 2.6?

**Comment by guruz** [comment]
@ckamm We can't take care of it since we don't provide ArchLinux packages. For the ownCloud client packages we ship this doesn't happen since we don't ship the bearer plugins.

> Is it even possible that a behaviour of the network manager could cause qt5-webkit to crash like that?

The bug is in Qt still, it's only triggered by your setup :( 
You can try to workaround it by renaming the ```bearer``` plugins in your Qt directory.

**Comment by ogoffart** [comment]
@doronbehar the official owncloud packages ship with Qt compiled without bearer manager.
This bug is in that part of Qt, and yes, is also potentially affecting any other Qt application.

I'm closing this issue in this bug tracker. Refer to the upstream issue: https://bugreports.qt.io/browse/QTBUG-58541
