### ISSUE TITLE
scary unreliability warning

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7305]
Client 260daily20190702 and later on windows 10

The client had synced with the server, then it was swiched off. 
When restarting, this message appears:

![image](https://user-images.githubusercontent.com/1108546/61043646-152bd100-a3d7-11e9-950c-5de4c98eb9f9.png)

As a user, I have no choice except accepting that owncloud is now unreliable. 
What can a user do to make it reliable again?

Here is a collection of client logs. Hope that is helpful.
[ownCloud-logdir.zip](https://github.com/owncloud/client/files/3381520/ownCloud-logdir.zip)

**Comment by ckamm** [comment]
I think it's due to a race condition in folder watcher startup.

**Comment by ckamm** [comment]
Do you have suggestions on how to improve the "it's not reliable, but should work anyway!" messaging, to make it less scary?

**Comment by ckamm** [comment]
Please test carefully, I couldn't reproduce the issue locally but think I understood what was happening from the logs.

**Comment by jnweiger** [comment]
Built from the PR, runs fine. No such messages seen. Now I cannot reproduce anymore. :-)

**Comment by jnweiger** [comment]
Thanks you! Let's assume it is fixed.

**Comment by ckamm** [comment]
Closing since it's already tested.

**Comment by HanaGemela** [comment]
Still broken in 2.6.0alpha2 (build 12128), macOS 10.14.5.
In the log there is: 
 07-16 11:56:11:049 [ warning gui.folder ]:	Folder watcher for "/Users/hana/ownCloud/" became unreliable: "The watcher did not receive a test notification."

**Comment by ckamm** [comment]
Doh, it doesn't work on OSX because the file watcher filters out changes done by the process itself. That makes testing the watcher on OSX harder and I'll disable it there.

**Comment by ckamm** [comment]
Relates to #7241

**Comment by ckamm** [comment]
@HanaGemela The test is now disabled on OSX. The warning should no longer be shown.

**Comment by ckamm** [comment]
forgot to merge, is now merged to 2.6.0

**Comment by HanaGemela** [comment]
Message not shown on macOS 10.14.6, client 2.6.0beta1 (build 12241)
