### ISSUE TITLE
Files and directories containing : or | are ignored

### ISSUE THREAD

**Issue by rikvdh** [owncloud/client#854]
### Expected behaviour

Files getting synced to my ownCloud server
### Actual behaviour

I see this occurring in the Linux client.
When I create files or directories containing | : > < ? or a few other characters, they are automatically ignored.

I already did some research and found this commit in csync:
http://git.csync.org/users/freitag/csync.git/commit/?id=e0807cba1b164fcf409cb71e3da2f8f7b88637a9

I don't know why this commit is there, creating files on Linux with | : < > \* ? is perfectly valid. :)

total 16
drwxr-xr-x  4 rik rik 4096 Aug 11 08:32 .
drwxr-xr-x 10 rik rik 4096 Aug 10 16:11 ..
-rw-r--r--  1 rik rik    0 Aug 11 08:22 abc*def
-rw-r--r--  1 rik rik    0 Aug 10 16:02 abc:def
-rw-r--r--  1 rik rik    0 Aug 11 08:21 abc>def
-rw-r--r--  1 rik rik    0 Aug 11 08:22 abc?def
drwxr-xr-x  2 rik rik 4096 Aug 11 08:22 abc|def
drwxr-xr-x  2 rik rik 4096 Aug 10 16:08 a|c
### Steps to reproduce
1. Install Linux client
2. Sync ownCloud
3. Create a file with: touch 'abc|def' and see it getting ignored :)
### Server configuration

not applicable, normal Debian Wheezy with apache2
### Client configuration

Client version: latest from git (but also occurs with 1.3.0)
Operating system: Debian Wheezy
OS language: en_US
Installation path of client: /usr/local/bin/owncloud
### Log

08-10 16:10:59:661 csync_ftw: Uniq ID from Database: test/a|c -> <NULL>
08-10 16:10:59:661 csync_walker: directory: /home/rik/ownCloud/test/a|c
08-10 16:10:59:661 _csync_detect_update: test/a|c excluded  (1)
08-10 16:10:59:661 _csync_detect_update: ==> file: test/a|c - hash 6527849599191992178, mtime: 1376143708
08-10 16:10:59:662 _csync_detect_update: file: test/a|c, instruction: INSTRUCTION_IGNORE <<=

**Comment by unamedplayer** [comment]
Howdy, just adding my voice to this. I've done some testing with Google Drive and they handle all kinds of odd characters via translation. The file names may not be consistent across platforms but no data is left unsynced which is very important IMHO.

Thank you for all the comments and pointing out the path forward.

**Comment by danimo** [comment]
fyi: This is being worked on for ownCloud Server 8.1 on a broader scope.

**Comment by unamedplayer** [comment]
Yay :) Thank you!

**Comment by unamedplayer** [comment]
@danimo , do you have any fresh info on this by any chance? I don't mean to pester but I've been keeping a close eye on all beta releases, we are now well into 8.1 and I don't see any indication that this is being addressed at the moment. Which is fine I'm not complaining :) but I'm wondering about current state of things is and also what you meant by "broader scope". Thank you!

**Comment by AshleyYakeley** [comment]
What's the status of this? The issue is closed, but it still appears to be a problem in 8.1?

**Comment by brevilo** [comment]
If I'm not mistaken it takes client 2.1 (soon to be released) for this to work with the 8.1 server...

**Comment by DCKcode** [comment]
This bug still affects me. I'm on OwnCloud 9.0.2 server (ZFS on FreeBSD) with client 2.1.1 on OS X. This bug has been present in all earlier versions I've used too. Has this really been resolved?

**Comment by dragotin** [comment]
@DeepDiver1975 isn't that supposed to be fixed with server 9.0.x? The client ignores these filenames only on win32.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 isn't that supposed to be fixed with server 9.0.x? The client ignores these filenames only on win32.

yes - the server is accepting file names depending on the server side filesystem.
On a posix server system only \ and / are not allowed - see https://github.com/owncloud/core/blob/master/lib/private/Files/Storage/Common.php#L519

**Comment by DeepDiver1975** [comment]
and this is implemented since 8.1

**Comment by erhan-** [comment]
I have the same issue on a debian jessie server with ubuntu client:

> |0|path/file:name.pdf|INST_NEW|Up|145795xxxx||3235xxx||6|The item is not synced because of previous errors: Error downloading https://web/remote.php/webdav/path/file:name.pdf - server replied: Internal Server Error (Invalid request for Invalid path, ":" is not allowed (InvalidPathException))|0|0|0|||INST_NONE|

**Comment by a-schild** [comment]
@erhan- what owncloud server & client versions are you using?

**Comment by erhan-** [comment]
Server: 9.0.2
Client: 2.2.0

Had multiple illogical problems with one specific client after client update to 2.2.0 but it all resolved after removing the account from the client and readding it again, resyncing in a new folder. Consider my problem as solved.

**Comment by mckaygerhard** [comment]
i used and have that problem, but moved to nextcloud and not any more. puff oc
