### ISSUE TITLE
ownCloud client is not respecting the system language on Linux

### ISSUE THREAD

**Issue by msvi** [owncloud/client#8722]
### Expected behaviour
ownCloud on Linux should respect the system language setting.

### Actual behaviour
ownCloud on Linux always uses English even if the system language is set to something else.

### Steps to reproduce
1. Change the system language to something other than English.
2. Start ownCloud

### Client configuration
Client version: 2.8.2

Operating system: Arch Linux

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Client package (From ownCloud or distro) (Linux only): distro

Installation path of client: /usr/bin/owncloud

### Logs

```
06-13 12:30:42:039 [ info gui.application ]:	"################## ownCloud locale:[de_DE] ui_lang:[] version:[2.8.2] os:[Arch Linux]"
06-13 12:30:42:041 [ info gui.application ]:	VFS suffix plugin is available
06-13 12:30:42:042 [ info gui.socketapi ]:	server started, listening at  "/run/user/1000/ownCloud/socket"
06-13 12:30:42:042 [ info gui.folder.manager ]:	setting remote poll timer interval to 30000 msec
06-13 12:30:42:109 [ info gui.account.manager ]:	Restored:  0  unknown certs.
06-13 12:30:42:136 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
06-13 12:30:42:136 [ info gui.folder.manager ]:	Setup folders from settings file
06-13 12:30:42:136 [ info sync.configfile ]:	Adding system ignore list to csync: "/etc/ownCloud/sync-exclude.lst"
06-13 12:30:42:143 [ info sync.database ]:	sqlite3 version "3.35.5"
06-13 12:30:42:143 [ info sync.database ]:	sqlite3 locking_mode= "exclusive"
06-13 12:30:42:143 [ info sync.database ]:	sqlite3 journal_mode= "wal"
06-13 12:30:42:143 [ info sync.database ]:	sqlite3 synchronous= "NORMAL"
```

### Other Information

I've downgraded to ownCloud 2.6.3. In this version the system language is respected. Starting from version 2.7 ownCloud always uses English. When I set the `LANG` variable to a locale that is not present on my system I get an error message indicating that ownCloud does in fact read that variable. But when I set it to a locale that is present on my system ownCloud silently falls back to English.

**Comment by gabi18** [comment]
Could you please check whether the package owncloud-client-l10n is installed.

**Comment by msvi** [comment]
There is no separate localization package but the qm files are installed in `/usr/share/owncloud/i18n`.

**Comment by gabi18** [comment]
I cannot reproduce the problem on openSUSE 15.2 with client version 2.8.2. When setting the env var LANG e.g. to de_DE.UTF-8 the client correctly shows german translations.

**Comment by gabi18** [comment]
You could try whether https://download.owncloud.com/desktop/ownCloud/daily/2.9/linux-appimage/ works on your system.

**Comment by TheOneRing** [comment]
2.9 introduced quite some changes to the localisation so it will be hard to compare the results.

**Comment by msvi** [comment]
The behaviour with the AppImage is the same, it's English but `LANG` is set to `de_DE.UTF-8`.

```
$ locale
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES=
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```
Other Qt apps correctly show the UI in German.

> Do you have former versions of the translation package available? Where do the translations come from?

The translations are packed as part of the owncloud package. I've tried with earlier versions from the archive and it works with 2.6 and earlier.

To confirm, with translation package you are referring to the qm files in `/usr/share/owncloud/i18n`? I've tried using the ownCloud 2.6 translation files with 2.8.2 but the UI stays in English.

**Comment by gabi18** [comment]
I can confirm that the AppImage doesn't respect the locale setting. I will open a separate issue for that.

**Comment by gabi18** [comment]
> To confirm, with translation package you are referring to the qm files in `/usr/share/owncloud/i18n`? I've tried using the ownCloud 2.6 translation files with 2.8.2 but the UI stays in English.

The version of the translation package must be the same as the client package. It seems that for 2.6 both packages were available.
Also for 2.8.2 you need to have  owncloud-client-l10n-2.8.2 and owncloud-client-2.8.2 installed.

**Comment by gabi18** [comment]
> For me it seems the `SHAREDIR` macro depends on the `DATADIR` CMake variable which is set to `DATA_INSTALL_DIR`. However, I'm not shure where this variable is set and I couldn't find anything about it in the CMake documentation.
@TheOneRing could you please have a look

**Comment by TheOneRing** [comment]
The SHAREDIR  mess was fixed in 2.9, we won't fix it in 2.8.

**Comment by msvi** [comment]
Thank you for the clarification. However, with owncloud 2.9 the language setting is still not respected. I've built from source and put the translation files in `/usr/share/ownCloud/i18n` (capital C).

The problem seems to be the this line in `src/gui/translations.cpp`:

```
return QStandardPaths::locate(QStandardPaths::DataLocation, translationDir, QStandardPaths::LocateDirectory);
```

This resolves to `/usr/share/ownCloud` and not `/usr/share/ownCloud/i18n`. I changed `QStandardPaths::DataLocation` to `QStandardPaths::AppDataLocation` and then the path was resolved correctly to `/usr/share/ownCloud/i18n`. The app correctly loaded the German translations.

@gabi18 I'm using the packages provided by my distribution. Because Arch uses its own package format, the packages are created from the source. Arch does not split the translation into a separate package but they are instead included in the `owncloud-client` package.

So, if the above mentioned issue is fixed the problem should be solved for the Arch package.

**Comment by TheOneRing** [comment]
> This resolves to `/usr/share/ownCloud` and not `/usr/share/ownCloud/i18n`. I changed `QStandardPaths::DataLocation` to `QStandardPaths::AppDataLocation` and then the path was resolved correctly to `/usr/share/ownCloud/i18n`. The app correctly loaded the German translations.

Is there a typo? We are looking for i18n in `DataLocation` so the i18n dir is unrelated to `AppDataLocation`
Also they appear to be identically https://doc.qt.io/qt-5/qstandardpaths.html



DataLocation | "~/.local/share/&lt;APPNAME&gt;", "/usr/local/share/&lt;APPNAME&gt;", "/usr/share/&lt;APPNAME&gt;"
-- | --






AppDataLocation | "~/.local/share/&lt;APPNAME&gt;", "/usr/local/share/&lt;APPNAME&gt;", "/usr/share/&lt;APPNAME&gt;"
-- | --

**Comment by msvi** [comment]
No typo in my comment. I don't know why it resolves correctly with `AppDataLocation` but not with `DataLocation`. Maybe a bug in Qt?
The only reason I tried that was because the docs mentioned that `DataLocation` is deprecated and `AppDataLocation` should be used instead.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/pull/8743

**Comment by msvi** [comment]
Shouldn't it be `AppDataLocation` (= `/usr/share/ownCloud`) and not `GenericDataLocation` (= `/usr/share`)?

**Comment by TheOneRing** [comment]
You are totally right

**Comment by zar3bski** [comment]
This old issue seem to come back: I encountered the same problem on Arch Linux with `owncloud-client-6.0.3.18040-1`
