### ISSUE TITLE
Removing Sync Connection broken

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#9791]
### Describe the bug

Startpoint is: one sync connection local folder `foo => /` on the server and local folder `bar => /bar`.  Note that the second sync connection syncs into a sub folder of the the first one, which is bad, but anyway...

If bar is syncing (ie. after it was just added and the first sync is happening) and the sync connection is removed through the menu item, strange things happen:
1. The sync connection bar is removed, and the real sync journal gets removed. However, a new journal gets created, perhaps by an upload job that finishes after the journal was removed in the first place.
2. The first sync connection `foo` went into the "wait" state because through bar's sync activity, it got changed (remember bar syncs into a sub folder of foo) and wants to sync. Once bar went away, foo could actually start to sync. The error is that that does not happen. The remaining sync connection remains in wait state (forever?).

### Expected behavior

Remove foo and just start to sync bar.

I am not sure if the cross-sync-setup is really needed to reproduce that, or if normal sync connection would show that fail as well.

### Client version number

Current master (3.0.0-git)

**Comment by jnweiger** [comment]
Cannot follow the steps to reproduce with 2.10.2-rc1.1 due to https://github.com/owncloud/client/issues/9954

**Comment by jnweiger** [comment]
> I am not sure if the cross-sync-setup is really needed to reproduce that, or if normal sync connection would show that fail as well.

I am afraid, it also happens with a single sync connection:

https://github.com/owncloud/client/issues/9954#issuecomment-1194151240

**Comment by dpapac** [comment]
On Ubuntu 20.04 Desktop-Client Version: 2.10.1:

I could reproduce this behavior a previously synced folder that and won't sync in a certain time.
A force sync could not resolve the issue in my case.

**Comment by jnweiger** [comment]
Um, this code change looks supiciously close to the issue we see here.
https://github.com/owncloud/client/blob/19c008d3f81879fd9201baa2da7588f95d3298e2/src/gui/folder.h#L106

@TheOneRing please double check, this is not causing collateral damage.

**Comment by TheOneRing** [comment]
You found that one issue in 2.10.2-rc1 which I mentioned and that is already fixed in 2.10.2 dailies.

**Comment by emma1382** [comment]
tested with /home/solveigs/Applications/ownCloud-2.11.0-rc1.8255.AppImage on Manjaro-Linux : 
- still broken

**Comment by TheOneRing** [comment]
@emma1382 the waiting status is unrelated to this issue.

**Comment by jnweiger** [comment]
Tested with 2.11.0-daily 2022-08-04 testpilotcloud:
* The db is always correctly removed, when trying to create havoc with multiple sync folders.
* The cyclic waiting problem almost always strikes. Followup in #9969

Confirmed fixed.
