### ISSUE TITLE
[QA] re-login hangs with 'no connection configured'

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9925]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Seen with 2.10.1-rc.1 (and earlier)

* start a temporary server with oauth2
* Connect client
* Cuit client
* Shut down server
* Restart client (on the next day)
* The account is "signed out" (aka logged out). OK
![image](https://user-images.githubusercontent.com/1108546/179172187-e44b9713-d9cf-47f3-a90a-9a68b7544c4c.png)

----

* Click account -> log in
* The message 'No <servername> connection configured`is shown. BAD
* Often this message only flashes briefly and gets replaced by `Obtaining authorization from browser`, but sometimes it hangs. BAD.
![image](https://user-images.githubusercontent.com/1108546/179172319-357f1457-fb01-4778-93af-c256ce5e926e.png)

----

* The account menu then offers a `log out` entry. This is odd, we are still logged out. 

Expected behaviour

* an error message is shown, when the account -> log in action fails
* The message 'No <servername> connection configured`is not shown. Connection information is obviously there, as the log in succeeds on the next attempt.
Workaorund
* Click account -> log out, the status message switches back to "signed out"
* Click account -> log in, the login succeeds (hopefully, never saw the failure twice in a row)

### Expected behavior

.

### Steps to reproduce the issue

.

### Screenshots

.

### Logs

.

### Client version number

.

### Desktop environment (Linux only)

.

### Client package version and origin (Linux only)

.

### Installation path (Windows only)

.

### Server information

.

### Additional context

.

**Comment by TheOneRing** [comment]
I don't expect to see that issue with 3.0 and its not a regression in 2.10 its been around for a while.
Logging out and back in solves the issue.

**Comment by TheOneRing** [comment]
@michaelstingl have you seen the issue with a up to date 3.0?

**Comment by michaelstingl** [comment]
> @michaelstingl have you seen the issue with a up to date 3.0?

Yes, I see it reliably at the first restart after a new connection was configured on macOS 12.5.1. @fmoc you had a look at it. what did you find out?

**Comment by TheOneRing** [comment]
Interesting as I thought we removed the "no connection configured" message

**Comment by michaelstingl** [comment]
@TheOneRing I was able to reproduce pretty reliably:
https://cloud.owncloud.com/index.php/f/5877873
(Screen recording, logs and config)

```
testpilotcloud 3.0.0.8504-daily20220909 14f97d
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

**Comment by TheOneRing** [comment]
Could you retest now that we got the dynamic registration fix merged?

**Comment by saw-jan** [comment]
This issue still exists and sometimes the connection is not configured within `60 seconds` (says the GUI test)

![Screenshot from 2022-11-07 10-00-18](https://user-images.githubusercontent.com/52366632/200225525-ab611c26-1c74-4b02-bfe5-7d93a4622215.png)
![ss](https://user-images.githubusercontent.com/52366632/200225551-79d03db1-a311-44b4-a473-596992185791.png)

Reports: [Report 1](https://cache.owncloud.com/public/owncloud/client/13574/guiReportUpload/index.html), [Report 2](https://cache.owncloud.com/public/owncloud/client/13574/guiReportUpload/index.html)

**Comment by TheOneRing** [comment]
@saw-jan could you provide the client logs for this?

**Comment by HanaGemela** [comment]
@saw-jan could you please provide log file with the error, screen recording or reliable steps to recreate?

**Comment by TheOneRing** [comment]
```
01:18:22:478 AUT stdout: 11-06 01:18:21:652 [ info gui.account.state ]:	AccountState connection status change:  OCC::ConnectionValidator::Undefined -> OCC::ConnectionValidator::CredentialsNotReady
01:18:22:478 AUT stdout: 11-06 01:18:21:652 [ warning sync.credentials.http.legacy ]:	Migrating old keychain entries failed "The name org.freedesktop.secrets was not provided by any .service files"
```
So I guess its a regression on the tests. This was fixed before.

**Comment by saw-jan** [comment]
> This is the squish server log of a failing scenario due to this issue: [serverlog.log](https://github.com/owncloud/client/files/9959469/serverlog.log)
> 
> Full squish server log is here https://cache.owncloud.com/public/owncloud/client/13580/guiReportUpload/serverlog.log

These logs were from the GUI tests run against the oC10 server.
<br>
> could you please provide log file with the error, screen recording or reliable steps to recreate?

I could only grab the logs from the test run and recently I haven't seen this failure (but if fails then this might be due to the reason Hanna mentioned above). Also, I couldn't recreate this issue manually both with oC10 and oCIS servers.

But there is a switch from `No connection configured` to another message during re-login.
With oC10:
`No connection configured` to `Connecting to ...`

[oc10.webm](https://user-images.githubusercontent.com/52366632/201596837-228dcb04-1050-43ac-a05d-337b3d49899c.webm)


With oCIS:
`No connection configured` to `Reauthorization required.`

[ocis.webm](https://user-images.githubusercontent.com/52366632/201596892-4ceef8c9-a44a-43fc-97f3-28cb114f1fbe.webm)

**Comment by individual-it** [comment]
So if the issue is not reproducible anymore I will close it and put it to "done", if it comes back we will have to reopen it and work on it again
